import { useEffect, useState } from 'react';
import { ArrowRight, Bot, CloudSun, Compass, Download, ExternalLink, Heart, Map as MapIcon, Navigation, ShieldCheck, Sparkles, Wind } from 'lucide-react';
import type { Location, Page, SavedPlace, Weather } from './types';
import { getWeather, quality } from './services';
import { Disclaimer, Header, Nav, Preferences, ResultCard, SearchBox, SourcePanel } from './components';
import { MapCanvas } from './MapCanvas';

export default function App(){const [page,setPage]=useState<Page>('home'),[location,setLocation]=useState<Location>(),[weather,setWeather]=useState<Weather>(),[saved,setSaved]=useState<SavedPlace[]>(()=>JSON.parse(localStorage.getItem('dzm-saved')||'[]')),[settings,setSettings]=useState(false);
 const choose=async(l:Location)=>{setLocation(l);setPage('map');setWeather(undefined);try{setWeather(await getWeather(l))}catch{}};
 const save=()=>{if(!location)return; const next=[{...location,id:crypto.randomUUID(),savedAt:new Date().toISOString(),score:weather?.score},...saved.filter(x=>x.name!==location.name)].slice(0,25);setSaved(next);localStorage.setItem('dzm-saved',JSON.stringify(next))};
 const geo=()=>navigator.geolocation?.getCurrentPosition(p=>choose({lat:p.coords.latitude,lng:p.coords.longitude,name:'My location'}));
 return <div className="app"><Header setSettings={()=>setSettings(true)}/>{page==='home'&&<Home onChoose={choose} geo={geo}/>} {page==='map'&&<MapPage location={location} weather={weather} choose={choose} save={save}/>} {page==='weather'&&<WeatherPage location={location} weather={weather} choose={choose}/>} {page==='ai'&&<AiPage location={location} weather={weather}/>} {page==='saved'&&<SavedPage saved={saved} choose={choose} remove={id=>{const n=saved.filter(x=>x.id!==id);setSaved(n);localStorage.setItem('dzm-saved',JSON.stringify(n))}}/>}{settings&&<Settings close={()=>setSettings(false)}/>}<Nav page={page} setPage={setPage}/><Preferences close={()=>{}}/></div>}
function Home({onChoose,geo}:{onChoose:(l:Location)=>void;geo:()=>void}){return <main className="home"><div className="orb one"/><div className="orb two"/><section className="hero"><div className="pill"><Sparkles size={14}/> Planning, not permission</div><h1>Know the air.<br/><i>Before</i> you fly.</h1><p>One calm, clear place to explore official drone-source coverage, flight weather, and the right questions to ask before takeoff.</p><SearchBox onLocation={onChoose} hero/><div className="heroButtons"><button className="primary" onClick={geo}><Navigation size={17}/> Use my location</button><button onClick={()=>onChoose({lat:52.52,lng:13.405,name:'Berlin, Germany'})}>Try Berlin <ArrowRight size={16}/></button></div></section><section className="featureGrid">{[[MapIcon,'Official source status','See exactly what is loaded — and what is not.'],[CloudSun,'Weather planning','Live wind, gusts, rain, clouds, and flight score.'],[Bot,'AI copilot, optional','Explains loaded context. Never grants legal permission.']].map(([I,t,d])=>{const Icon=I as typeof MapIcon;return <article key={String(t)}><Icon/><b>{t as string}</b><span>{d as string}</span></article>})}</section><Disclaimer/></main>}
function MapPage({location,weather,choose,save}:{location?:Location;weather?:Weather;choose:(l:Location)=>void;save:()=>void}){return <main className="mapPage"><MapCanvas location={location} onPick={choose}/><div className="mapSearch"><SearchBox onLocation={choose}/></div><div className="mapPanel"><div className="eyebrow">LIVE DRONE ZONES</div><b>DIPUL · Germany</b><p>Official WMS layers are drawn over satellite imagery. Toggle them with the DIPUL control.</p><a href="https://dipul.bund.de/homepage/en/information/geographical-zones/web-map-service-wms/" target="_blank" rel="noreferrer">Source & terms ↗</a></div>{location?<ResultCard location={location} weather={weather} onSave={save}/>:<div className="emptyCheck"><Compass/><b>Choose a point on the map</b><span>We’ll check source coverage and weather context.</span></div>}</main>}
function WeatherPage({location,weather,choose}:{location?:Location;weather?:Weather;choose:(l:Location)=>void}){return <main className="page weatherPage"><div className="sectionTitle"><div><div className="eyebrow">FLIGHT FORECAST</div><h1>Find the better window.</h1></div><CloudSun size={38}/></div>{location?<><div className="locationChip"><Navigation size={15}/>{location.name}</div>{weather?<section className="weatherCard"><div><span>FLIGHT SCORE</span><strong>{weather.score}</strong><b>{quality(weather.score)}</b></div><div className="metrics"><Metric icon={<Wind/>} label="Wind" value={`${weather.wind} km/h`}/><Metric icon={<Wind/>} label="Gusts" value={`${weather.gusts} km/h`}/><Metric icon={<CloudSun/>} label="Cloud" value={`${weather.cloud}%`}/><Metric icon={<CloudSun/>} label="Temp" value={`${weather.temperature}°C`}/></div></section>:<p>Getting current forecast…</p>}<div className="timeline">{['Now','+1h','+2h','+3h','+4h','+5h'].map((x,i)=><div className={i===0?'selected':''} key={x}><small>{x}</small><CloudSun size={19}/><b>{weather?Math.max(0,weather.score-i*3):'—'}</b></div>)}</div><Disclaimer/></>:<section className="emptyPage"><CloudSun/><h2>Pick a location first</h2><SearchBox onLocation={choose}/></section>}</main>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div>{icon}<small>{label}</small><b>{value}</b></div>}
function AiPage({location,weather}:{location?:Location;weather?:Weather}){return <main className="page aiPage"><div className="sectionTitle"><div><div className="eyebrow">OPTIONAL COPILOT</div><h1>Ask clearer questions.</h1></div><Bot size={38}/></div><section className="aiCard"><div className="aiAvatar"><Sparkles/></div><h2>AI flight check is off</h2><p>The static app never sends your location to an AI service by default. You can later connect a user-provided key or secure proxy.</p><div className="context">{location?<>Context ready: <b>{location.name}</b>{weather&&<> · weather score <b>{weather.score}</b></>}</>:<>Choose a map location to prepare context.</>}</div><button disabled>Enable AI in Settings <ArrowRight size={15}/></button></section><section className="questions"><b>When enabled, it can help explain:</b>{['Can I fly here?','Explain this zone','What is the weather risk?','Show official source'].map(x=><button key={x}>{x}</button>)}</section><Disclaimer/></main>}
function SavedPage({saved,choose,remove}:{saved:SavedPlace[];choose:(l:Location)=>void;remove:(id:string)=>void}){return <main className="page"><div className="sectionTitle"><div><div className="eyebrow">LOCAL ONLY</div><h1>Saved & sources</h1></div><Heart size={38}/></div>{saved.length?<section className="savedList">{saved.map(s=><article key={s.id}><button className="savedMain" onClick={()=>choose(s)}><b>{s.name}</b><span>{s.lat.toFixed(4)}, {s.lng.toFixed(4)} · {s.score??'—'}/100 weather</span></button><button className="delete" onClick={()=>remove(s.id)}>Remove</button></article>)}</section>:<section className="emptyPage"><Heart/><h2>No saved places yet</h2><p>Flight spots and checked coordinates stay on this device.</p></section>}<SourcePanel/><Disclaimer/></main>}
function Settings({close}:{close:()=>void}){return <div className="modalShade"><section className="settings"><button className="close" onClick={close}>×</button><div className="eyebrow">PREFERENCES</div><h2>Your device, your choices.</h2><label>Theme<select><option>Dark</option><option>Light</option><option>System</option></select></label><label>Units<select><option>Metric</option><option>Imperial</option></select></label><label>Language<select><option>English</option><option>Deutsch</option><option>Español</option><option>Français</option></select></label><p>Saved places and preferences are stored locally. No analytics are enabled.</p><button className="danger" onClick={()=>{localStorage.removeItem('dzm-saved');close();location.reload()}}>Delete local saved places</button></section></div>}
