import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Bot, Camera, Check, Cloud, CloudRain, CloudSun, Compass, Database, Download, Eye, Heart, Layers3, Map as MapIcon, Navigation, Send, ShieldCheck, Sparkles, Trash2, WifiOff, Wind } from 'lucide-react';
import type { AppSettings, Location, Page, SavedPlace, Weather, WeatherHour, ZoneInfo } from './types';
import { getWeather, quality } from './services';
import { getOfficialZoneInfo } from './zoneInfo';
import { createOfflinePack, downloadGeoJson, getOfflinePacks } from './offline';
import { Disclaimer, Header, Nav, Preferences, ResultCard, SearchBox, SourcePanel } from './components';
import { MapCanvas, type MapCanvasHandle } from './MapCanvas';
import { normalizeLanguage, SUPPORTED_LANGUAGES } from './languages';
import { FlightPlanner, type FlightPoint } from './FlightPlanner';
import { answerFlightQuestion } from './localAssistant';
import { screenCopy } from './screenCopy';

export default function App(){
 const [page,setPage]=useState<Page>('home'),[location,setLocation]=useState<Location>(),[weather,setWeather]=useState<Weather>(),[zoneInfo,setZoneInfo]=useState<ZoneInfo>(),[weatherError,setWeatherError]=useState(''),[saved,setSaved]=useState<SavedPlace[]>(()=>JSON.parse(localStorage.getItem('dzm-saved')||'[]')),[settingsOpen,setSettingsOpen]=useState(false);
 const [appSettings,setAppSettings]=useState<AppSettings>(()=>{try{const stored=JSON.parse(localStorage.getItem('aeris-settings')||'{}');return{renderDetail:'balanced',glassOpacity:.72,reducedMotion:false,...stored,language:stored.defaultLanguageVersion===2?normalizeLanguage(stored.language):'en'}}catch{return{renderDetail:'balanced',glassOpacity:.72,reducedMotion:false,language:'en'}}});
 const chooseRequest=useRef(0);
 const choose=async(l:Location)=>{const request=++chooseRequest.current;setLocation(l);setPage('map');setWeather(undefined);setZoneInfo(undefined);setWeatherError('');const [weatherResult,zoneResult]=await Promise.allSettled([getWeather(l),getOfficialZoneInfo(l,appSettings.language)]);if(request!==chooseRequest.current)return;if(weatherResult.status==='fulfilled')setWeather(weatherResult.value);else setWeatherError('Live weather is temporarily unavailable.');if(zoneResult.status==='fulfilled')setZoneInfo(zoneResult.value)};
 const save=()=>{if(!location)return;const next=[{...location,id:crypto.randomUUID(),savedAt:new Date().toISOString(),score:weather?.score},...saved.filter(x=>Math.abs(x.lat-location.lat)>.00001||Math.abs(x.lng-location.lng)>.00001)].slice(0,50);setSaved(next);localStorage.setItem('dzm-saved',JSON.stringify(next))};
 const remove=(id:string)=>{const next=saved.filter(x=>x.id!==id);setSaved(next);localStorage.setItem('dzm-saved',JSON.stringify(next))};
 const geo=()=>navigator.geolocation?.getCurrentPosition(p=>choose({lat:p.coords.latitude,lng:p.coords.longitude,name:'My location'}));
 const updateSettings=(next:AppSettings)=>{setAppSettings(next);localStorage.setItem('aeris-settings',JSON.stringify({...next,defaultLanguageVersion:2}))};
 useEffect(()=>{document.documentElement.lang=appSettings.language},[appSettings.language]);
 return <div className={`app page-${page} ${appSettings.reducedMotion?'reducedMotion':''}`} style={{'--glass-opacity':appSettings.glassOpacity} as React.CSSProperties}><div className="ambient a"/><div className="ambient b"/><Header setSettings={()=>setSettingsOpen(true)}/><div className="pageTransition" key={page}>{page==='home'&&<Home onChoose={choose} geo={geo} openMap={()=>setPage('map')} language={appSettings.language}/>} {page==='map'&&<MapPage location={location} weather={weather} weatherError={weatherError} zoneInfo={zoneInfo} choose={choose} save={save} settings={appSettings}/>} {page==='weather'&&<WeatherPage location={location} weather={weather} error={weatherError} choose={choose} language={appSettings.language}/>} {page==='ai'&&<AiPage location={location} weather={weather} zoneInfo={zoneInfo} saved={saved.length}/>} {page==='saved'&&<SavedPage saved={saved} choose={choose} remove={remove}/>}</div>{settingsOpen&&<Settings settings={appSettings} update={updateSettings} close={()=>setSettingsOpen(false)}/>}<Nav page={page} setPage={setPage} language={appSettings.language}/><Preferences close={()=>{}}/></div>
}

function Home({onChoose,geo,openMap,language}:{onChoose:(l:Location)=>void;geo:()=>void;openMap:()=>void;language:string}){const c=screenCopy(language);return <main className="home homeCinematic">
  <section className="cinematicHero">
    <div className="heroPhoto" aria-hidden="true"/>
    <div className="heroShade" aria-hidden="true"/>
    <div className="coastLabel"><i/><span>{c.coverage}</span><b>{c.sources}</b></div>
    <div className="hero">
      <div className="pill"><Sparkles size={14}/> {c.pill}</div>
      <h1>{c.hero1}<br/><i>{c.hero2}</i></h1>
      <p>{c.heroBody}</p>
      <SearchBox onLocation={onChoose} hero language={language}/>
      <div className="heroButtons"><button className="primary" onClick={geo}><Navigation size={17}/> {c.useLocation}</button><button className="exploreButton" onClick={openMap}><MapIcon size={17}/> {c.openMap} <ArrowRight size={16}/></button></div>
      <div className="trustRow"><span><ShieldCheck/>{c.officialContext}</span><span><CloudSun/>{c.forecast36}</span><span><Database/>{c.private}</span></div>
    </div>
    <div className="flightReadout liquid"><div><span className="liveDot"/> {c.ready}</div><b>{c.safer}</b><p>{c.flightBody}</p><button onClick={openMap} aria-label={c.openMap}><ArrowRight/></button></div>
    <div className="scrollCue"><span>{c.discover}</span><i/></div>
  </section>
  <section className="homeBelow">
    <div className="sectionIntro"><div className="eyebrow">{c.contextEyebrow}</div><h2>{c.decision1}<br/>{c.decision2}</h2><p>{c.contextBody}</p></div>
    <section className="featureGrid">{[[MapIcon,c.airspace,c.airspaceBody],[CloudSun,c.weatherWindows,c.weatherBody],[Bot,c.copilot,c.copilotBody]].map(([I,title,description],index)=>{const Icon=I as typeof MapIcon;return <article style={{'--delay':`${index*90}ms`} as React.CSSProperties} key={String(title)}><small>0{index+1}</small><span><Icon/></span><b>{title as string}</b><p>{description as string}</p><button onClick={openMap} aria-label={`${c.discover} ${String(title)}`}><ArrowRight/></button></article>})}</section>
    <div className="homeNote"><Compass/><div><b>{c.orientation}</b><p>{c.orientationBody}</p></div></div>
    <Disclaimer/>
  </section>
</main>}

function MapPage({location,weather,weatherError,zoneInfo,choose,save,settings}:{location?:Location;weather?:Weather;weatherError:string;zoneInfo?:ZoneInfo;choose:(l:Location)=>void;save:()=>void;settings:AppSettings}){
 const[offline,setOffline]=useState(false),[resultOpen,setResultOpen]=useState(true),[plannerMode,setPlannerMode]=useState(false),[exportStatus,setExportStatus]=useState('');
 const[planPoints,setPlanPoints]=useState<FlightPoint[]>(()=>{try{return JSON.parse(localStorage.getItem('aeris-flight-plan')||'[]')}catch{return[]}});
 const mapCanvasRef=useRef<MapCanvasHandle>(null);
 useEffect(()=>{if(location)setResultOpen(true)},[location?.lat,location?.lng]);
 const updatePlan=(points:FlightPoint[])=>{setPlanPoints(points);localStorage.setItem('aeris-flight-plan',JSON.stringify(points))};
 const addPlanPoint=(point:Location)=>updatePlan([...planPoints,{...point,id:crypto.randomUUID()}].slice(-40));
 const makePack=async()=>{if(!location)return;await createOfflinePack(location,weather,zoneInfo);setOffline(true)};
 const runMapExport=async(kind:'geojson'|'snapshot')=>{setExportStatus(kind==='geojson'?'Preparing visible overlays…':'Rendering clean snapshot…');try{if(kind==='geojson')mapCanvasRef.current?.downloadVisibleGeoJson(location?.name);else await mapCanvasRef.current?.downloadCleanSnapshot(location?.name);setExportStatus(kind==='geojson'?'Visible overlay GeoJSON downloaded.':'Clean map PNG downloaded.')}catch(reason){setExportStatus(reason instanceof Error?reason.message:'Export failed.')}window.setTimeout(()=>setExportStatus(''),3200)};
 return <main className="mapPage"><MapCanvas ref={mapCanvasRef} location={location} weather={weather} weatherError={weatherError} onPick={choose} settings={settings} plannerMode={plannerMode} planPoints={planPoints} onPlanPoint={addPlanPoint}/><div className="mapSearch"><SearchBox onLocation={choose} language={settings.language}/></div><div className="mapPanel liquid"><div className="eyebrow">LIVE AIRSPACE LAYERS</div><b><span className="liveDot"/> Germany · Spain · France · UK · Switzerland · US · Canada · Denmark · Luxembourg · Ireland · Sweden</b><p>Spain uses all three public ENAIRE datasets with large regional zones softened so local restrictions stay readable. Canada renders reusable federal airports and national parks; its protected NAV CANADA-derived airspace remains on the official map.</p><a href="https://www.avinor.no/en/practical-info/drone/dronekart/" target="_blank" rel="noreferrer">Open Norway’s official map ↗</a><a href="https://map.dronespace.at/" target="_blank" rel="noreferrer">Open Austria’s official Dronespace map ↗</a><button onClick={makePack} disabled={!location}>{offline?<><Check/>Saved offline</>:<><Download/>Save offline snapshot</>}</button><button onClick={()=>runMapExport('geojson')}><Download/>Download visible overlay GeoJSON</button><button onClick={()=>runMapExport('snapshot')}><Camera/>Download clean map PNG</button>{exportStatus&&<small className="exportStatus">{exportStatus}</small>}<small>GeoJSON includes every visible vector feature plus references for visible raster overlays. The PNG contains the rendered map and overlays without the app panels. Canada’s protected NRC/NAV CANADA data is not copied.</small></div><FlightPlanner active={plannerMode} points={planPoints} selected={location} language={settings.language} onToggle={()=>setPlannerMode(value=>!value)} onUndo={()=>updatePlan(planPoints.slice(0,-1))} onClear={()=>updatePlan([])} onCheck={choose} onAddSelected={addPlanPoint}/>{!plannerMode&&(location&&resultOpen?<ResultCard location={location} weather={weather} zoneInfo={zoneInfo} onSave={save} onClose={()=>setResultOpen(false)} language={settings.language}/>:location?<button className="reopenResult liquid" onClick={()=>setResultOpen(true)}>Show location check</button>:<div className="emptyCheck liquid"><Compass/><b>Touch anywhere</b><span>Weather and official source details will meet you there.</span></div>)}</main>
}

const WeatherIcon=({hour}:{hour:WeatherHour})=>hour.rainProbability>55?<CloudRain/>:hour.cloud>75?<Cloud/>:<CloudSun/>;
function WeatherPage({location,weather,error,choose,language}:{location?:Location;weather?:Weather;error:string;choose:(l:Location)=>void;language:string}){
 const [selected,setSelected]=useState(0),c=screenCopy(language);
 const hour=weather?.hourly[selected];
 const best=useMemo(()=>weather?.hourly.slice(0,24).map((x,i)=>({...x,index:i})).sort((a,b)=>b.score-a.score).slice(0,3)??[],[weather]);
 return <main className="page weatherPage"><div className="weatherHero"><div><div className="eyebrow">{c.weatherEyebrow}</div><h1>{c.calm}</h1><p>{c.tapHour}</p></div><div className="weatherOrb"><CloudSun/><span>{hour?.temperature??weather?.temperature??'—'}°</span></div></div>{location?<><div className="locationChip"><Navigation size={15}/>{location.name}<small>{weather?.timezone}</small></div>{error&&<div className="errorCard">{error}</div>}{weather&&hour?<><section className="weatherDashboard liquid"><div className="scoreRing" style={{'--score':hour.score} as React.CSSProperties}><div><strong>{hour.score}</strong><span>{c.flightScore}</span></div></div><div className="weatherSummary"><small>{new Date(hour.time).toLocaleString(language,{weekday:'long',hour:'2-digit',minute:'2-digit'})}</small><h2>{quality(hour.score)}</h2><p>{hour.wind<20?c.manageable:c.windCare} {hour.rainProbability<25?c.lowRain:c.rainElevated}</p></div><div className="metrics"><Metric icon={<Wind/>} label={c.wind} value={`${hour.wind} km/h`} hint={`Gusts ${hour.gusts}`}/><Metric icon={<CloudRain/>} label={c.rain} value={`${hour.rainProbability}%`} hint={`${hour.rain} mm`}/><Metric icon={<Cloud/>} label={c.cloud} value={`${hour.cloud}%`} hint={hour.isDay?c.daylight:c.afterDark}/><Metric icon={<Eye/>} label={c.visibility} value={`${Math.round(hour.visibility/1000)} km`} hint={`${hour.temperature}°C`}/></div></section><div className="bestWindows"><div><div className="eyebrow">{c.best}</div><b>{c.topToday}</b></div>{best.map(item=><button key={item.time} onClick={()=>setSelected(item.index)}><span>{new Date(item.time).toLocaleTimeString(language,{hour:'2-digit',minute:'2-digit'})}</span><b>{item.score}</b></button>)}</div><div className="timeline rich">{weather.hourly.slice(0,24).map((item,index)=><button className={index===selected?'selected':''} onClick={()=>setSelected(index)} key={item.time}><small>{index===0?c.now:new Date(item.time).toLocaleTimeString(language,{hour:'2-digit'})}</small><WeatherIcon hour={item}/><b>{item.score}</b><span>{item.wind} km/h</span></button>)}</div><Disclaimer/></>:<div className="loadingCard">{c.reading}</div>}</>:<section className="emptyPage liquid"><CloudSun/><h2>{c.chooseFlight}</h2><p>{c.chooseFlightBody}</p><SearchBox onLocation={choose} language={language}/></section>}</main>
}
function Metric({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string}){return <div className="metric">{icon}<span>{label}</span><b>{value}</b><small>{hint}</small></div>}

function AiPage({location,weather,zoneInfo,saved}:{location?:Location;weather?:Weather;zoneInfo?:ZoneInfo;saved:number}){
 const [question,setQuestion]=useState(''),[messages,setMessages]=useState<{question:string;answer:string}[]>([]);
 const ask=(text=question)=>{const clean=text.trim();if(!clean)return;setQuestion('');setMessages(value=>[...value,{question:clean,answer:answerFlightQuestion({question:clean,location,weather,zoneInfo})}])};
 return <main className="page aiPage"><div className="aiHeader"><div><div className="eyebrow">AERIS COPILOT · GROUNDED FLIGHT CONTEXT</div><h1>Turn map data into clarity.</h1><p>Ask about the loaded location, weather and official-zone context. It works locally with no account, API key or external AI provider.</p></div><div className="aiPulse"><Bot/><i/></div></div><section className="copilotGrid"><div className="chatPanel liquid"><div className="chatTop"><div className="aiAvatar"><Sparkles/></div><div><b>Aeris Copilot</b><span><i/> Ready on this device</span></div></div><div className="chatBody">{messages.length===0?<div className="assistantMessage"><b>Ready when you are.</b><p>{location?`I have grounded context for ${location.name}${weather?` and its ${weather.score}/100 weather score`:''}.`:'Select a location on the map, then ask a question.'}</p></div>:messages.map((message,index)=><div key={index} className="conversation"><div className="userMessage">{message.question}</div><div className="assistantMessage"><b>Aeris Copilot</b><p>{message.answer}</p></div></div>)}</div><div className="chatInput"><input value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>event.key==='Enter'&&ask()} placeholder="Ask about this flight context…"/><button onClick={()=>ask()} aria-label="Send"><Send/></button></div></div><aside className="contextRail"><div className="localAssistantCard liquid"><small>ON-DEVICE · NO API KEY</small><b>Always available</b><p>Answers are produced from the weather and airspace context already loaded in the app. No login or provider configuration is required.</p></div><div className="contextCard liquid"><small>ACTIVE CONTEXT</small><b>{location?.name??'No location selected'}</b><span>{weather?`${weather.score}/100 weather · ${weather.wind} km/h wind`:'Weather waiting'}</span><span>{zoneInfo?`${zoneInfo.zones.length} zones · ${zoneInfo.sourceName}`:'Official source waiting'}</span><span>{saved} saved {saved===1?'place':'places'}</span></div><div className="quickActions"><small>QUICK QUESTIONS</small>{['Can I fly here?','Explain the visible zones','What is the weather risk?','Best time in 24 hours?'].map(text=><button key={text} onClick={()=>ask(text)}>{text}<ArrowRight/></button>)}</div><div className="aiSafety"><ShieldCheck/><p>No legal permission claims. Always verify the responsible official aviation source.</p></div></aside></section></main>
}

function SavedPage({saved,choose,remove}:{saved:SavedPlace[];choose:(l:Location)=>void;remove:(id:string)=>void}){const [tab,setTab]=useState<'places'|'sources'|'storage'>('places'),offline=getOfflinePacks();return <main className="page savedPage"><div className="savedHeader"><div><div className="eyebrow">YOUR FLIGHT LIBRARY</div><h1>Places worth returning to.</h1><p>Everything here stays in this browser.</p></div><Heart/></div><div className="segmented"><button className={tab==='places'?'active':''} onClick={()=>setTab('places')}><Heart/> Places <span>{saved.length}</span></button><button className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}><Layers3/> Sources</button><button className={tab==='storage'?'active':''} onClick={()=>setTab('storage')}><Database/> Offline <span>{offline.length}</span></button></div>{tab==='places'&&(saved.length?<section className="savedGrid">{saved.map((s,index)=><article className="savedCard liquid" key={s.id}><div className={`savedMapThumb thumb${index%3}`}><Navigation/><span>{s.lat.toFixed(3)}, {s.lng.toFixed(3)}</span></div><div className="savedContent"><small>SAVED {new Date(s.savedAt).toLocaleDateString()}</small><h3>{s.name}</h3><div className="savedScore"><CloudSun/><b>{s.score??'—'}</b><span>last weather score</span></div><div><button onClick={()=>choose(s)}>Open map <ArrowRight/></button><button className="delete" onClick={()=>remove(s.id)} aria-label={`Remove ${s.name}`}><Trash2/></button></div></div></article>)}</section>:<section className="emptyPage liquid"><div className="emptyOrbit"><Heart/><i/></div><h2>Your next flight spot starts on the map.</h2><p>Tap a location, review its context, then save it here.</p><button onClick={()=>choose({lat:52.52,lng:13.405,name:'Berlin, Germany'})}>Explore an example <ArrowRight/></button></section>)}{tab==='sources'&&<SourcePanel/>}{tab==='storage'&&<section className="offlineLibrary">{offline.length?offline.map(pack=><article className="offlineCard liquid" key={pack.id}><WifiOff/><div><small>OFFLINE SNAPSHOT · {new Date(pack.savedAt).toLocaleDateString()}</small><h3>{pack.name}</h3><p>{pack.weather?`${pack.weather.score}/100 weather · ${pack.weather.wind} km/h wind`:'No weather snapshot'} · {pack.zoneInfo?.zones.length??0} saved zones</p><span>{pack.notice}</span></div><div className="offlineActions"><button onClick={()=>choose(pack.location)}>Open <ArrowRight/></button><button onClick={()=>downloadGeoJson(pack)}><Download/> GeoJSON</button></div></article>):<div className="storagePanel liquid"><WifiOff/><div><h2>No offline snapshots yet</h2><p>Choose a map point and use “Save offline snapshot”. Satellite tiles and live WMS layers are not downloaded.</p></div></div>}<button className="danger" onClick={()=>{localStorage.removeItem('dzm-offline-packs');location.reload()}}>Delete offline snapshots</button></section>}<Disclaimer/></main>}

function Settings({settings,update,close}:{settings:AppSettings;update:(settings:AppSettings)=>void;close:()=>void}){const selected=SUPPORTED_LANGUAGES.find(([code])=>code===settings.language),[languageQuery,setLanguageQuery]=useState(selected?.[1]??settings.language),c=screenCopy(settings.language);return <div className="modalShade"><section className="settings liquid"><button className="close" onClick={close}>×</button><div className="eyebrow">{c.preferences}</div><h2>{c.preferencesTitle}</h2><label>{c.language}<input className="languageSearch" list="aeris-language-list" value={languageQuery} onChange={event=>{const typed=event.target.value;setLanguageQuery(typed);const value=typed.toLowerCase();const match=SUPPORTED_LANGUAGES.find(([code,name])=>code===value||name.toLowerCase()===value);if(match)update({...settings,language:match[0]})}} onBlur={()=>setLanguageQuery(SUPPORTED_LANGUAGES.find(([code])=>code===settings.language)?.[1]??settings.language)} placeholder={c.searchLanguages}/><datalist id="aeris-language-list">{SUPPORTED_LANGUAGES.map(([code,name])=><option value={name} key={code}>{code.toUpperCase()}</option>)}</datalist><small>{c.languageHelp}</small></label><label>{c.overlayDetail}<select value={settings.renderDetail} onChange={event=>update({...settings,renderDetail:event.target.value as AppSettings['renderDetail']})}><option value="efficient">Efficient · nearby essentials</option><option value="balanced">Balanced · recommended</option><option value="maximum">Maximum · farther and denser</option></select><small>{c.detailHelp}</small></label><label className="glassSlider"><span>{c.glass} <b>{Math.round(settings.glassOpacity*100)}%</b></span><input type="range" min=".38" max=".92" step=".01" value={settings.glassOpacity} onChange={event=>update({...settings,glassOpacity:Number(event.target.value)})}/><i style={{width:`${settings.glassOpacity*100}%`}}/></label><label className="toggleSetting"><span>{c.reduce}<small>{c.reduceHelp}</small></span><input type="checkbox" checked={settings.reducedMotion} onChange={event=>update({...settings,reducedMotion:event.target.checked})}/></label><button className="primary" onClick={close}><Check/> {c.savePreferences}</button></section></div>}
