import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Bot, Check, Cloud, CloudRain, CloudSun, Compass, Database, Download, Eye, Heart, Layers3, Map as MapIcon, Navigation, Send, ShieldCheck, Sparkles, Trash2, WifiOff, Wind } from 'lucide-react';
import type { AppSettings, Location, Page, SavedPlace, Weather, WeatherHour, ZoneInfo } from './types';
import { getWeather, quality } from './services';
import { getOfficialZoneInfo } from './zoneInfo';
import { createOfflinePack, downloadGeoJson, getOfflinePacks } from './offline';
import { Disclaimer, Header, Nav, Preferences, ResultCard, SearchBox, SourcePanel } from './components';
import { MapCanvas } from './MapCanvas';
import { normalizeLanguage, SUPPORTED_LANGUAGES } from './languages';

export default function App(){
 const [page,setPage]=useState<Page>('home'),[location,setLocation]=useState<Location>(),[weather,setWeather]=useState<Weather>(),[zoneInfo,setZoneInfo]=useState<ZoneInfo>(),[weatherError,setWeatherError]=useState(''),[saved,setSaved]=useState<SavedPlace[]>(()=>JSON.parse(localStorage.getItem('dzm-saved')||'[]')),[settingsOpen,setSettingsOpen]=useState(false);
 const [appSettings,setAppSettings]=useState<AppSettings>(()=>{try{return{renderDetail:'balanced',glassOpacity:.72,reducedMotion:false,language:normalizeLanguage(),...JSON.parse(localStorage.getItem('aeris-settings')||'{}')}}catch{return{renderDetail:'balanced',glassOpacity:.72,reducedMotion:false,language:normalizeLanguage()}}});
 const chooseRequest=useRef(0);
 const choose=async(l:Location)=>{const request=++chooseRequest.current;setLocation(l);setPage('map');setWeather(undefined);setZoneInfo(undefined);setWeatherError('');const [weatherResult,zoneResult]=await Promise.allSettled([getWeather(l),getOfficialZoneInfo(l,appSettings.language)]);if(request!==chooseRequest.current)return;if(weatherResult.status==='fulfilled')setWeather(weatherResult.value);else setWeatherError('Live weather is temporarily unavailable.');if(zoneResult.status==='fulfilled')setZoneInfo(zoneResult.value)};
 const save=()=>{if(!location)return;const next=[{...location,id:crypto.randomUUID(),savedAt:new Date().toISOString(),score:weather?.score},...saved.filter(x=>Math.abs(x.lat-location.lat)>.00001||Math.abs(x.lng-location.lng)>.00001)].slice(0,50);setSaved(next);localStorage.setItem('dzm-saved',JSON.stringify(next))};
 const remove=(id:string)=>{const next=saved.filter(x=>x.id!==id);setSaved(next);localStorage.setItem('dzm-saved',JSON.stringify(next))};
 const geo=()=>navigator.geolocation?.getCurrentPosition(p=>choose({lat:p.coords.latitude,lng:p.coords.longitude,name:'My location'}));
 const updateSettings=(next:AppSettings)=>{setAppSettings(next);localStorage.setItem('aeris-settings',JSON.stringify(next))};
 useEffect(()=>{document.documentElement.lang=appSettings.language},[appSettings.language]);
 return <div className={`app page-${page} ${appSettings.reducedMotion?'reducedMotion':''}`} style={{'--glass-opacity':appSettings.glassOpacity} as React.CSSProperties}><div className="ambient a"/><div className="ambient b"/><Header setSettings={()=>setSettingsOpen(true)}/><div className="pageTransition" key={page}>{page==='home'&&<Home onChoose={choose} geo={geo} openMap={()=>setPage('map')} language={appSettings.language}/>} {page==='map'&&<MapPage location={location} weather={weather} weatherError={weatherError} zoneInfo={zoneInfo} choose={choose} save={save} settings={appSettings}/>} {page==='weather'&&<WeatherPage location={location} weather={weather} error={weatherError} choose={choose} language={appSettings.language}/>} {page==='ai'&&<AiPage location={location} weather={weather} saved={saved.length}/>} {page==='saved'&&<SavedPage saved={saved} choose={choose} remove={remove}/>}</div>{settingsOpen&&<Settings settings={appSettings} update={updateSettings} close={()=>setSettingsOpen(false)}/>}<Nav page={page} setPage={setPage} language={appSettings.language}/><Preferences close={()=>{}}/></div>
}

function Home({onChoose,geo,openMap,language}:{onChoose:(l:Location)=>void;geo:()=>void;openMap:()=>void;language:string}){return <main className="home homeCinematic">
  <section className="cinematicHero">
    <div className="heroPhoto" aria-hidden="true"/>
    <div className="heroShade" aria-hidden="true"/>
    <div className="coastLabel"><i/><span>LIVE COVERAGE</span><b>European airspace sources</b></div>
    <div className="hero">
      <div className="pill"><Sparkles size={14}/> Flight context, without the guesswork</div>
      <h1>Know the sky<br/><i>before you fly.</i></h1>
      <p>Choose a place. See official airspace sources and the weather window together—before your drone leaves the ground.</p>
      <SearchBox onLocation={onChoose} hero language={language}/>
      <div className="heroButtons"><button className="primary" onClick={geo}><Navigation size={17}/> Use my location</button><button className="exploreButton" onClick={openMap}><MapIcon size={17}/> Open live map <ArrowRight size={16}/></button></div>
      <div className="trustRow"><span><ShieldCheck/>Official-source context</span><span><CloudSun/>36-hour forecast</span><span><Database/>Private by default</span></div>
    </div>
    <div className="flightReadout liquid"><div><span className="liveDot"/> READY TO PLAN</div><b>Find a safer flight window</b><p>Airspace layers, wind, rain and visibility in one calm view.</p><button onClick={openMap} aria-label="Open the live map"><ArrowRight/></button></div>
    <div className="scrollCue"><span>Discover</span><i/></div>
  </section>
  <section className="homeBelow">
    <div className="sectionIntro"><div className="eyebrow">ONE LOCATION · THE CONTEXT THAT MATTERS</div><h2>From pin drop to<br/>flight decision.</h2><p>Aeris keeps the essentials together, so you spend less time switching tabs and more time understanding the place.</p></div>
    <section className="featureGrid">{[[MapIcon,'Airspace context','See verified live layers and jump to the responsible official source.'],[CloudSun,'Weather windows','Compare the next 36 hours for wind, gusts, rain and visibility.'],[Bot,'Grounded copilot','Turn the data already loaded into clear, honest explanations.']].map(([I,t,d],index)=>{const Icon=I as typeof MapIcon;return <article style={{'--delay':`${index*90}ms`} as React.CSSProperties} key={String(t)}><small>0{index+1}</small><span><Icon/></span><b>{t as string}</b><p>{d as string}</p><button onClick={openMap} aria-label={`Explore ${String(t)}`}><ArrowRight/></button></article>})}</section>
    <div className="homeNote"><Compass/><div><b>Built for orientation, not authorization.</b><p>Always confirm restrictions and permission with the official aviation authority before takeoff.</p></div></div>
    <Disclaimer/>
  </section>
</main>}

function MapPage({location,weather,weatherError,zoneInfo,choose,save,settings}:{location?:Location;weather?:Weather;weatherError:string;zoneInfo?:ZoneInfo;choose:(l:Location)=>void;save:()=>void;settings:AppSettings}){const[offline,setOffline]=useState(false),[resultOpen,setResultOpen]=useState(true);useEffect(()=>{if(location)setResultOpen(true)},[location?.lat,location?.lng]);const makePack=async(exportFile=false)=>{if(!location)return;const pack=await createOfflinePack(location,weather,zoneInfo);setOffline(true);if(exportFile)downloadGeoJson(pack)};return <main className="mapPage"><MapCanvas location={location} weather={weather} weatherError={weatherError} onPick={choose} settings={settings}/><div className="mapSearch"><SearchBox onLocation={choose} language={settings.language}/></div><div className="mapPanel liquid"><div className="eyebrow">LIVE AIRSPACE LAYERS</div><b><span className="liveDot"/> Germany · Spain · France · UK · Switzerland · US · Canada · Denmark · Luxembourg · Ireland · Sweden</b><p>Spain uses all three public ENAIRE zone datasets with readable semantic colors. Switzerland loads FOCA’s complete open UAS geozones. Canada shows reusable federal airports and national parks.</p><a href="https://www.avinor.no/en/practical-info/drone/dronekart/" target="_blank" rel="noreferrer">Open Norway’s official map ↗</a><a href="https://map.dronespace.at/" target="_blank" rel="noreferrer">Open Austria’s official Dronespace map ↗</a><button onClick={()=>makePack(false)} disabled={!location}>{offline?<><Check/>Saved offline</>:<><Download/>Save offline snapshot</>}</button><button onClick={()=>makePack(true)} disabled={!location}><Download/>Download DJI-style GeoJSON</button><small>Canada’s protected NAV CANADA-derived database and Norway’s protected service remain official-link-only.</small></div>{location&&resultOpen?<ResultCard location={location} weather={weather} zoneInfo={zoneInfo} onSave={save} onClose={()=>setResultOpen(false)} language={settings.language}/>:location?<button className="reopenResult liquid" onClick={()=>setResultOpen(true)}>Show location check</button>:<div className="emptyCheck liquid"><Compass/><b>Touch anywhere</b><span>Weather and official source details will meet you there.</span></div>}</main>}

const WeatherIcon=({hour}:{hour:WeatherHour})=>hour.rainProbability>55?<CloudRain/>:hour.cloud>75?<Cloud/>:<CloudSun/>;
function WeatherPage({location,weather,error,choose,language}:{location?:Location;weather?:Weather;error:string;choose:(l:Location)=>void;language:string}){const [selected,setSelected]=useState(0);const hour=weather?.hourly[selected];const best=useMemo(()=>weather?.hourly.slice(0,24).map((x,i)=>({...x,index:i})).sort((a,b)=>b.score-a.score).slice(0,3)??[],[weather]);return <main className="page weatherPage"><div className="weatherHero"><div><div className="eyebrow">36-HOUR FLIGHT FORECAST</div><h1>Find your calm window.</h1><p>Tap any hour to compare conditions for the exact selected location.</p></div><div className="weatherOrb"><CloudSun/><span>{hour?.temperature??weather?.temperature??'—'}°</span></div></div>{location?<><div className="locationChip"><Navigation size={15}/>{location.name}<small>{weather?.timezone}</small></div>{error&&<div className="errorCard">{error}</div>}{weather&&hour?<><section className="weatherDashboard liquid"><div className="scoreRing" style={{'--score':hour.score} as React.CSSProperties}><div><strong>{hour.score}</strong><span>FLIGHT SCORE</span></div></div><div className="weatherSummary"><small>{new Date(hour.time).toLocaleString(language, {weekday:'long',hour:'2-digit',minute:'2-digit'})}</small><h2>{quality(hour.score)}</h2><p>{hour.wind<20?'Manageable sustained wind.':'Wind needs extra care.'} {hour.rainProbability<25?'Low rain risk.':'Rain risk is elevated.'}</p></div><div className="metrics"><Metric icon={<Wind/>} label="Wind" value={`${hour.wind} km/h`} hint={`Gusts ${hour.gusts}`}/><Metric icon={<CloudRain/>} label="Rain" value={`${hour.rainProbability}%`} hint={`${hour.rain} mm`}/><Metric icon={<Cloud/>} label="Cloud" value={`${hour.cloud}%`} hint={hour.isDay?'Daylight':'After dark'}/><Metric icon={<Eye/>} label="Visibility" value={`${Math.round(hour.visibility/1000)} km`} hint={`${hour.temperature}°C`}/></div></section><div className="bestWindows"><div><div className="eyebrow">BEST WINDOWS</div><b>Top conditions today</b></div>{best.map(x=><button key={x.time} onClick={()=>setSelected(x.index)}><span>{new Date(x.time).toLocaleTimeString(language,{hour:'2-digit',minute:'2-digit'})}</span><b>{x.score}</b></button>)}</div><div className="timeline rich">{weather.hourly.slice(0,24).map((x,i)=><button className={i===selected?'selected':''} onClick={()=>setSelected(i)} key={x.time}><small>{i===0?'Now':new Date(x.time).toLocaleTimeString(language,{hour:'2-digit'})}</small><WeatherIcon hour={x}/><b>{x.score}</b><span>{x.wind} km/h</span></button>)}</div><Disclaimer/></>:<div className="loadingCard">Reading the atmosphere…</div>}</>:<section className="emptyPage liquid"><CloudSun/><h2>Choose where you want to fly</h2><p>Paste coordinates or use your location on the map.</p><SearchBox onLocation={choose} language={language}/></section>}</main>}
function Metric({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint:string}){return <div className="metric">{icon}<span>{label}</span><b>{value}</b><small>{hint}</small></div>}

function AiPage({location,weather,saved}:{location?:Location;weather?:Weather;saved:number}){const [question,setQuestion]=useState(''),[messages,setMessages]=useState<string[]>([]);const ask=(text=question)=>{if(!text.trim())return;setMessages(m=>[...m,text.trim()]);setQuestion('')};return <main className="page aiPage"><div className="aiHeader"><div><div className="eyebrow">AERIS COPILOT · PRIVATE BY DEFAULT</div><h1>Turn map data into clarity.</h1><p>The assistant is designed to explain only the location, weather and official sources already loaded by the app.</p></div><div className="aiPulse"><Bot/><i/></div></div><section className="copilotGrid"><div className="chatPanel liquid"><div className="chatTop"><div className="aiAvatar"><Sparkles/></div><div><b>Aeris Copilot</b><span><i/> Local preview mode</span></div></div><div className="chatBody">{messages.length===0?<div className="assistantMessage"><b>Ready when you are.</b><p>{location?`I have context for ${location.name}${weather?` and a weather score of ${weather.score}`:''}.`:'Select a location on the map and I’ll prepare its context.'}</p></div>:messages.map((m,i)=><div key={i} className="conversation"><div className="userMessage">{m}</div><div className="assistantMessage"><b>Preview response</b><p>{location?`For ${location.name}, I can explain the loaded source coverage and weather, but a secure AI provider is not connected yet.`:'Choose a location first so the answer can stay grounded.'}</p></div></div>)}</div><div className="chatInput"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask about this flight context…"/><button onClick={()=>ask()} aria-label="Send"><Send/></button></div></div><aside className="contextRail"><div className="contextCard liquid"><small>ACTIVE CONTEXT</small><b>{location?.name??'No location selected'}</b><span>{weather?`${weather.score}/100 weather · ${weather.wind} km/h wind`:'Weather waiting'}</span><span>{location?'Official source lookup ready':'Map point required'}</span><span>{saved} saved {saved===1?'place':'places'}</span></div><div className="quickActions"><small>QUICK QUESTIONS</small>{['Can I fly here?','Explain the visible zones','What is the weather risk?','Best time in 24 hours?'].map(x=><button key={x} onClick={()=>ask(x)}>{x}<ArrowRight/></button>)}</div><div className="aiSafety"><ShieldCheck/><p>No legal permission claims. No secret API key in the browser.</p></div></aside></section></main>}

function SavedPage({saved,choose,remove}:{saved:SavedPlace[];choose:(l:Location)=>void;remove:(id:string)=>void}){const [tab,setTab]=useState<'places'|'sources'|'storage'>('places'),offline=getOfflinePacks();return <main className="page savedPage"><div className="savedHeader"><div><div className="eyebrow">YOUR FLIGHT LIBRARY</div><h1>Places worth returning to.</h1><p>Everything here stays in this browser.</p></div><Heart/></div><div className="segmented"><button className={tab==='places'?'active':''} onClick={()=>setTab('places')}><Heart/> Places <span>{saved.length}</span></button><button className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}><Layers3/> Sources</button><button className={tab==='storage'?'active':''} onClick={()=>setTab('storage')}><Database/> Offline <span>{offline.length}</span></button></div>{tab==='places'&&(saved.length?<section className="savedGrid">{saved.map((s,index)=><article className="savedCard liquid" key={s.id}><div className={`savedMapThumb thumb${index%3}`}><Navigation/><span>{s.lat.toFixed(3)}, {s.lng.toFixed(3)}</span></div><div className="savedContent"><small>SAVED {new Date(s.savedAt).toLocaleDateString()}</small><h3>{s.name}</h3><div className="savedScore"><CloudSun/><b>{s.score??'—'}</b><span>last weather score</span></div><div><button onClick={()=>choose(s)}>Open map <ArrowRight/></button><button className="delete" onClick={()=>remove(s.id)} aria-label={`Remove ${s.name}`}><Trash2/></button></div></div></article>)}</section>:<section className="emptyPage liquid"><div className="emptyOrbit"><Heart/><i/></div><h2>Your next flight spot starts on the map.</h2><p>Tap a location, review its context, then save it here.</p><button onClick={()=>choose({lat:52.52,lng:13.405,name:'Berlin, Germany'})}>Explore an example <ArrowRight/></button></section>)}{tab==='sources'&&<SourcePanel/>}{tab==='storage'&&<section className="offlineLibrary">{offline.length?offline.map(pack=><article className="offlineCard liquid" key={pack.id}><WifiOff/><div><small>OFFLINE SNAPSHOT · {new Date(pack.savedAt).toLocaleDateString()}</small><h3>{pack.name}</h3><p>{pack.weather?`${pack.weather.score}/100 weather · ${pack.weather.wind} km/h wind`:'No weather snapshot'} · {pack.zoneInfo?.zones.length??0} saved zones</p><span>{pack.notice}</span></div><div className="offlineActions"><button onClick={()=>choose(pack.location)}>Open <ArrowRight/></button><button onClick={()=>downloadGeoJson(pack)}><Download/> GeoJSON</button></div></article>):<div className="storagePanel liquid"><WifiOff/><div><h2>No offline snapshots yet</h2><p>Choose a map point and use “Save offline snapshot”. Satellite tiles and live WMS layers are not downloaded.</p></div></div>}<button className="danger" onClick={()=>{localStorage.removeItem('dzm-offline-packs');location.reload()}}>Delete offline snapshots</button></section>}<Disclaimer/></main>}

function Settings({settings,update,close}:{settings:AppSettings;update:(settings:AppSettings)=>void;close:()=>void}){const selected=SUPPORTED_LANGUAGES.find(([code])=>code===settings.language),[languageQuery,setLanguageQuery]=useState(selected?.[1]??settings.language);return <div className="modalShade"><section className="settings liquid"><button className="close" onClick={close}>×</button><div className="eyebrow">MAP & GLASS PREFERENCES</div><h2>Choose how much Aeris renders.</h2><label>Language<input className="languageSearch" list="aeris-language-list" value={languageQuery} onChange={event=>{const typed=event.target.value;setLanguageQuery(typed);const value=typed.toLowerCase();const match=SUPPORTED_LANGUAGES.find(([code,name])=>code===value||name.toLowerCase()===value);if(match)update({...settings,language:match[0]})}} onBlur={()=>setLanguageQuery(SUPPORTED_LANGUAGES.find(([code])=>code===settings.language)?.[1]??settings.language)} placeholder="Search languages"/><datalist id="aeris-language-list">{SUPPORTED_LANGUAGES.map(([code,name])=><option value={name} key={code}>{code.toUpperCase()}</option>)}</datalist><small>Search by language name. Place search, official-map handoffs and key navigation labels use this language.</small></label><label>Overlay detail<select value={settings.renderDetail} onChange={event=>update({...settings,renderDetail:event.target.value as AppSettings['renderDetail']})}><option value="efficient">Efficient · nearby essentials</option><option value="balanced">Balanced · recommended</option><option value="maximum">Maximum · farther and denser</option></select><small>Maximum begins country overlays farther out and requests denser weather and airspace detail.</small></label><label className="glassSlider"><span>Liquid glass transparency <b>{Math.round(settings.glassOpacity*100)}%</b></span><input type="range" min=".38" max=".92" step=".01" value={settings.glassOpacity} onChange={event=>update({...settings,glassOpacity:Number(event.target.value)})}/><i style={{width:`${settings.glassOpacity*100}%`}}/></label><label className="toggleSetting"><span>Reduce motion<small>Stops the liquid selector stretch and cinematic drift.</small></span><input type="checkbox" checked={settings.reducedMotion} onChange={event=>update({...settings,reducedMotion:event.target.checked})}/></label><button className="primary" onClick={close}><Check/> Save preferences</button></section></div>}
