import { useEffect, useMemo, useState } from 'react';
import { Bot, CloudSun, Heart, Home, Layers3, Map, Search, Settings, ShieldAlert, Sparkles, X } from 'lucide-react';
import type { Page, Location, Weather } from './types';
import { sources, sourceFor, type Source } from './data/sources';
import { parseCoordinates, quality } from './services';

export function Logo({compact=false}:{compact?:boolean}) { return <div className="brand" aria-label="Aeris Airspace"><svg viewBox="0 0 44 44" role="img"><defs><linearGradient id="logoGlow" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#e9ffd9"/><stop offset="1" stopColor="#74f296"/></linearGradient></defs><path d="M22 4 38 13v18L22 40 6 31V13Z" fill="none" stroke="url(#logoGlow)" strokeWidth="2"/><path d="M13 25c5-1 7-4 9-11 2 7 4 10 9 11-5 1-7 3-9 7-2-4-4-6-9-7Z" fill="url(#logoGlow)"/><circle cx="22" cy="22" r="3" fill="#07120f"/></svg>{!compact&&<span><b>AERIS</b><small>DRONE AIRSPACE</small></span>}</div> }

export const Disclaimer=()=> <div className="disclaimer"><ShieldAlert size={15}/><span>This is not legal clearance. Check the official national aviation source before takeoff.</span></div>;
const pageMeta: {id:Page; label:string; icon:typeof Home}[]=[{id:'home',label:'Home',icon:Home},{id:'map',label:'Map',icon:Map},{id:'weather',label:'Weather',icon:CloudSun},{id:'ai',label:'AI Check',icon:Bot},{id:'saved',label:'Saved',icon:Heart}];
export function Nav({page,setPage}:{page:Page;setPage:(p:Page)=>void}) {return <nav className="dock" aria-label="Main navigation">{pageMeta.map(x=>{const I=x.icon;return <button className={page===x.id?'active':''} onClick={()=>setPage(x.id)} aria-label={x.label} aria-current={page===x.id?'page':undefined} key={x.id}><span className="navIcon"><I size={19}/></span><span className="navLabel">{x.label}</span></button>})}</nav>}
export function SearchBox({onLocation,hero=false}:{onLocation:(l:Location)=>void;hero?:boolean}) {const [value,setValue]=useState('');const [error,setError]=useState(''); const submit=()=>{const l=parseCoordinates(value);if(l){setError('');onLocation(l)}else setError('Try coordinates like 52.5200, 13.4050');}; return <div className={'searchWrap '+(hero?'heroSearch':'')}><Search size={19}/><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Paste coordinates to check anywhere" aria-label="Coordinates"/><button onClick={submit}>Check <span>location</span></button>{error&&<small>{error}</small>}</div>}
export function ResultCard({location,weather,onSave}:{location:Location;weather?:Weather;onSave:()=>void}) {const source=sourceFor(location.lat,location.lng);return <aside className="resultCard liquid"><div className="sheetHandle"/><div className="eyebrow">LIVE FLIGHT CONTEXT</div><h2>{location.name}</h2><div className={'status '+(source?'caution':'unknown')}><span/>{source?'Official German overlay visible':'Coverage not loaded'}</div><p>{source?'DIPUL raster zones are visible on the map. Select the source link for authoritative details and conditions.':'No reusable official zone layer is loaded here. Open the national source before flight.'}</p>{weather&&<div className="weatherline"><CloudSun size={19}/><div><b>{weather.score}/100 · {quality(weather.score)}</b><span>{weather.wind} km/h wind · {weather.rainProbability}% rain</span></div></div>}<div className="cardActions"><button onClick={onSave}><Heart size={16}/> Save location</button>{source&&<a href={source.url} target="_blank" rel="noreferrer">Official source ↗</a>}</div><Disclaimer/></aside>}

export function SourcePanel(){const [registry,setRegistry]=useState<Source[]>(sources),[query,setQuery]=useState(''),[expanded,setExpanded]=useState(false);useEffect(()=>{fetch(`${import.meta.env.BASE_URL}data/sources/countries.json`).then(r=>r.ok?r.json():[]).then((rows:unknown[])=>setRegistry(rows.map((row:any)=>({code:row.countryCode,country:row.countryName,name:row.sourceName,status:String(row.status).replaceAll('_',' '),url:row.officialMapUrl,detail:row.warnings?.[0]})))).catch(()=>{})},[]);const shown=useMemo(()=>registry.filter(s=>(s.country+s.name).toLowerCase().includes(query.toLowerCase())),[registry,query]);const visible=expanded?shown:shown.slice(0,6);return <section className="sources liquid"><div className="sourceHead"><div><div className="eyebrow">OFFICIAL DIRECTORY · {registry.length} COUNTRIES</div><h2>Know what is actually loaded.</h2></div><Layers3/></div><div className="sourceSearch"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a country or authority"/></div><div className="sourceGrid">{visible.map(s=><article key={s.code}><div className="countryCode">{s.code}</div><div><b>{s.country}</b><span className="sourceStatus">{s.status}</span><p>{s.name}</p><a href={s.url} target="_blank" rel="noreferrer">Open official source ↗</a></div></article>)}</div>{shown.length>6&&<button className="wideButton" onClick={()=>setExpanded(!expanded)}>{expanded?'Show fewer sources':`Explore all ${shown.length} sources`}</button>}</section>}
export function Preferences({close}:{close:()=>void}){const [open,setOpen]=useState(true);useEffect(()=>{if(localStorage.getItem('dzm-consent'))setOpen(false)},[]); if(!open)return null;const dismiss=()=>{localStorage.setItem('dzm-consent','yes');setOpen(false);close()};return <div className="consent liquid"><button className="icon" onClick={dismiss} aria-label="Close privacy notice"><X size={16}/></button><Sparkles size={20}/><b>Private by default.</b><p>Preferences and saved places stay on this device. No tracking cookies.</p><button onClick={dismiss}>Continue</button></div>}
export function Header({setSettings}:{setSettings:()=>void}) {return <header><Logo/><button className="icon liquid" onClick={setSettings} aria-label="Settings"><Settings size={19}/></button></header>}
