import { useEffect, useState } from 'react';
import { Bot, CloudSun, Compass, Heart, Home, Layers3, Map, Menu, Search, Settings, ShieldAlert, Sparkles, X } from 'lucide-react';
import type { Page, Location, Weather } from './types';
import { sources, sourceFor } from './data/sources';
import { parseCoordinates, quality } from './services';

export const Disclaimer=()=> <div className="disclaimer"><ShieldAlert size={15}/> This is not legal clearance. Check the official national aviation source before takeoff.</div>;
const pageMeta: {id:Page; label:string; icon:typeof Home}[]=[{id:'home',label:'Home',icon:Home},{id:'map',label:'Map',icon:Map},{id:'weather',label:'Weather',icon:CloudSun},{id:'ai',label:'AI Check',icon:Bot},{id:'saved',label:'Saved',icon:Heart}];
export function Nav({page,setPage}:{page:Page;setPage:(p:Page)=>void}) {return <nav className="dock">{pageMeta.map(x=>{const I=x.icon;return <button className={page===x.id?'active':''} onClick={()=>setPage(x.id)} aria-label={x.label} key={x.id}><I size={19}/><span>{x.label}</span></button>})}</nav>}
export function SearchBox({onLocation,hero=false}:{onLocation:(l:Location)=>void;hero?:boolean}) {const [value,setValue]=useState('');const [error,setError]=useState(''); const submit=()=>{const l=parseCoordinates(value);if(l){setError('');onLocation(l)}else setError('Enter coordinates such as 52.5200, 13.4050');}; return <div className={'searchWrap '+(hero?'heroSearch':'')}><Search size={20}/><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()} placeholder="Search coordinates or paste a location"/><button onClick={submit}>Check</button>{error&&<small>{error}</small>}</div>}
export function ResultCard({location,weather,onSave}:{location:Location;weather?:Weather;onSave:()=>void}) {const source=sourceFor(location.lat,location.lng);return <aside className="resultCard"><div className="eyebrow">FLIGHT CHECK · LIVE CONTEXT</div><h2>{location.name}</h2><div className={'status '+(source?'caution':'unknown')}>{source?'Official overlay available':'Unknown — source coverage pending'}</div><p>{source?<>Germany is configured with the official DIPUL WMS overlay. A WMS visual layer is available; this MVP does not turn it into a legal decision.</>:<>No loaded restriction was found at this point. This does not mean automatic permission to fly; normal drone laws and local rules still apply.</>}</p>{weather&&<div className="weatherline"><CloudSun size={18}/><b>{weather.score}/100</b> {quality(weather.score)} · {weather.wind} km/h wind</div>}<div className="cardActions"><button onClick={onSave}><Heart size={16}/> Save place</button>{source&&<a href={source.url} target="_blank">Official source ↗</a>}</div><Disclaimer/></aside>}
export function SourcePanel(){return <section className="sources"><div className="sectionTitle"><div><div className="eyebrow">DATA TRANSPARENCY</div><h2>Official source registry</h2></div><Layers3/></div>{sources.map(s=><article key={s.code}><b>{s.country}</b><span className="sourceStatus">{s.status}</span><p>{s.name} · {s.detail}</p><a href={s.url} target="_blank">Open official source ↗</a></article>)}</section>}
export function Preferences({close}:{close:()=>void}){const [open,setOpen]=useState(true);useEffect(()=>{if(localStorage.getItem('dzm-consent'))setOpen(false)},[]); if(!open)return null;return <div className="consent"><button className="icon" onClick={()=>{localStorage.setItem('dzm-consent','yes');setOpen(false);close()}}><X size={16}/></button><b>Your map, kept local.</b><p>This app stores preferences and saved places on your device. The basic version uses no tracking cookies.</p><button onClick={()=>{localStorage.setItem('dzm-consent','yes');setOpen(false)}}>Got it</button></div>}
export function Header({setSettings}:{setSettings:()=>void}) {return <header><div className="brand"><span>◉</span> AIRSPACE</div><button className="icon" onClick={setSettings} aria-label="Settings"><Settings size={19}/></button></header>}
