export type CountryRule={label:string;value:string;detail?:string};
export type CountryRuleSet={heading:string;scope:string;rules:CountryRule[];caveat:string;sourceLabel:string;countryName:string;links:{label:string;url:string}[]};

// Country-wide baseline only. Point-specific geographical zones still take precedence.
const germany:Record<string,CountryRuleSet>={
 en:{heading:'Country-wide baseline rules',scope:'Germany · EU open category',countryName:'Germany',rules:[
  {label:'Maximum height',value:'120 m',detail:'From the closest point of the surface in the open category.'},
  {label:'Visual line of sight',value:'Keep the drone in direct visual line of sight throughout the flight.'},
  {label:'Crowds',value:'Do not fly over assemblies of people in the open category.'},
  {label:'Operator registration',value:'Required for drones from 250 g, camera-equipped drones under 250 g (unless toys), and specific-category operations.'},
  {label:'Liability insurance',value:'Required for drone operations in Germany.'}
 ],caveat:'This is a general baseline, not flight clearance. German geographical zones can impose stricter limits or require permission. Check the current official map and rules before flying.',sourceLabel:'Official rules',links:[{label:'Germany · dipul',url:'https://dipul.de/homepage/en/information/general/legal-bases/'},{label:'EU open category · EASA',url:'https://www.easa.europa.eu/en/domains/drones-air-mobility/operating-drone/open-category-low-risk-civil-drones'}]},
 de:{heading:'Landesweit geltende Grundregeln',scope:'Deutschland · EU-Open-Kategorie',countryName:'Deutschland',rules:[
  {label:'Maximale Höhe',value:'120 m',detail:'In der offenen Kategorie höchstens 120 m vom nächstgelegenen Punkt der Erdoberfläche.'},
  {label:'Sichtverbindung',value:'Die Drohne muss während des gesamten Flugs in direkter Sichtverbindung bleiben.'},
  {label:'Menschenansammlungen',value:'In der offenen Kategorie nicht über Menschenansammlungen fliegen.'},
  {label:'Betreiberregistrierung',value:'Erforderlich ab 250 g, bei Kameradrohnen unter 250 g (außer Spielzeug) und in der speziellen Kategorie.'},
  {label:'Haftpflichtversicherung',value:'Für Drohnenflüge in Deutschland vorgeschrieben.'}
 ],caveat:'Dies sind allgemeine Grundregeln, keine Flugfreigabe. Geografische Gebiete in Deutschland können strengere Grenzen oder eine Genehmigung verlangen. Prüfe vor dem Flug die aktuelle offizielle Karte und Rechtslage.',sourceLabel:'Offizielle Regeln',links:[{label:'Deutschland · dipul',url:'https://dipul.de/homepage/de/informationen/allgemein/rechtliche-grundlagen/'},{label:'EU-Open-Kategorie · EASA',url:'https://www.easa.europa.eu/en/domains/drones-air-mobility/operating-drone/open-category-low-risk-civil-drones'}]},
 es:{heading:'Reglas generales del país',scope:'Alemania · categoría abierta de la UE',countryName:'Alemania',rules:[{label:'Altura máxima',value:'120 m',detail:'En categoría abierta, desde el punto más cercano de la superficie.'},{label:'Contacto visual',value:'Mantén contacto visual directo con el dron durante todo el vuelo.'},{label:'Multitudes',value:'No sobrevueles concentraciones de personas en categoría abierta.'},{label:'Registro del operador',value:'Obligatorio desde 250 g, para drones con cámara de menos de 250 g (salvo juguetes) y en categoría específica.'},{label:'Seguro de responsabilidad',value:'Obligatorio para operar drones en Alemania.'}],caveat:'Es una referencia general, no una autorización de vuelo. Las zonas geográficas alemanas pueden imponer límites más estrictos o exigir permiso. Consulta el mapa y las normas oficiales vigentes antes de volar.',sourceLabel:'Normas oficiales',links:[{label:'Alemania · dipul',url:'https://dipul.de/homepage/en/information/general/legal-bases/'},{label:'Categoría abierta de la UE · EASA',url:'https://www.easa.europa.eu/en/domains/drones-air-mobility/operating-drone/open-category-low-risk-civil-drones'}]},
 fr:{heading:'Règles générales du pays',scope:'Allemagne · catégorie ouverte de l’UE',countryName:'Allemagne',rules:[{label:'Hauteur maximale',value:'120 m',detail:'En catégorie ouverte, depuis le point le plus proche de la surface.'},{label:'Contact visuel',value:'Gardez le drone en contact visuel direct pendant tout le vol.'},{label:'Foules',value:'Ne survolez pas de rassemblements de personnes en catégorie ouverte.'},{label:'Enregistrement de l’exploitant',value:'Obligatoire dès 250 g, pour les drones avec caméra de moins de 250 g (sauf jouets) et en catégorie spécifique.'},{label:'Assurance responsabilité civile',value:'Obligatoire pour exploiter un drone en Allemagne.'}],caveat:'Il s’agit d’un cadre général, pas d’une autorisation de vol. Les zones géographiques allemandes peuvent imposer des limites plus strictes ou exiger une autorisation. Consultez la carte et les règles officielles à jour avant le vol.',sourceLabel:'Règles officielles',links:[{label:'Allemagne · dipul',url:'https://dipul.de/homepage/en/information/general/legal-bases/'},{label:'Catégorie ouverte de l’UE · EASA',url:'https://www.easa.europa.eu/en/domains/drones-air-mobility/operating-drone/open-category-low-risk-civil-drones'}]},
 it:{heading:'Regole generali del paese',scope:'Germania · categoria aperta UE',countryName:'Germania',rules:[{label:'Altezza massima',value:'120 m',detail:'Nella categoria aperta, dal punto più vicino della superficie.'},{label:'Contatto visivo',value:'Mantieni il drone sempre in contatto visivo diretto durante il volo.'},{label:'Assembramenti',value:'Nella categoria aperta non sorvolare assembramenti di persone.'},{label:'Registrazione dell’operatore',value:'Obbligatoria da 250 g, per droni con fotocamera sotto i 250 g (salvo giocattoli) e nella categoria specifica.'},{label:'Assicurazione di responsabilità',value:'Obbligatoria per l’uso dei droni in Germania.'}],caveat:'Queste sono regole generali, non un’autorizzazione al volo. Le zone geografiche tedesche possono imporre limiti più severi o richiedere un permesso. Prima di volare, consulta la mappa e le norme ufficiali aggiornate.',sourceLabel:'Norme ufficiali',links:[{label:'Germania · dipul',url:'https://dipul.de/homepage/en/information/general/legal-bases/'},{label:'Categoria aperta UE · EASA',url:'https://www.easa.europa.eu/en/domains/drones-air-mobility/operating-drone/open-category-low-risk-civil-drones'}]}
};

const localeNames:Record<string,string>={nl:'Duitsland',da:'Tyskland',no:'Tyskland',sv:'Tyskland',fi:'Saksa',pt:'Alemanha',pl:'Niemcy',cs:'Německo',sk:'Nemecko',hu:'Németország',ro:'Germania',bg:'Германия',el:'Γερμανία',hr:'Njemačka',sl:'Nemčija',et:'Saksamaa',lv:'Vācija',lt:'Vokietija',ga:'An Ghearmáin',rm:'Germania'};
const english=germany.en;
export function countryRuleSet(countryCode:string|undefined,language:string):CountryRuleSet|undefined{
 if(countryCode!=='DE')return undefined;
 const locale=language.toLowerCase().split('-')[0],localized=germany[locale]??english;
 if(germany[locale])return localized;
 return {...english,countryName:localeNames[locale]??english.countryName,scope:`${localeNames[locale]??english.countryName} · EU open category`};
}
