export type Page = 'home' | 'map' | 'weather' | 'ai' | 'saved';
export type RenderDetail = 'efficient' | 'balanced' | 'maximum';
export type AppSettings = {
  renderDetail: RenderDetail;
  glassOpacity: number;
  reducedMotion: boolean;
  terrain3d: boolean;
  showAi: boolean;
  language: string;
};
export type Location = { lat: number; lng: number; name: string };
export type WeatherHour = { time:string; temperature:number; wind:number; gusts:number; rain:number; rainProbability:number; cloud:number; visibility:number; score:number; isDay:boolean };
export type Weather = { temperature: number; wind: number; gusts: number; rain: number; rainProbability:number; cloud: number; visibility:number; score: number; hourly:WeatherHour[]; timezone:string };
export type ZoneDetail = {
  id:string;
  name:string;
  originalName?:string;
  nameLocalizedLanguage?:string;
  type:string;
  categoryCode?:string;
  severity?:'blocked'|'authorization'|'conditional'|'warning'|'information'|'unknown';
  message?:string;
  originalMessage?:string;
  messageLocalizedLanguage?:string;
  pilotAction?:string;
  lower?:string;
  upper?:string;
  legalReference?:string;
  contact?:string;
  authority?:string;
  officialLayerName?:string;
  layerCode?:string;
  source:string;
  sourceUrl?:string;
  updated?:string;
};
export type ZoneInfo = { countryCode:string; countryName:string; sourceName:string; sourceUrl:string; status:'loaded'|'none'|'unsupported'|'error'; zones:ZoneDetail[]; checkedAt:string; warning:string };
export type SavedWeatherSummary = {
  score:number;
  temperature:number;
  wind:number;
  gusts:number;
  rainProbability:number;
};
export type SavedAirspaceSummary = {
  countryCode:string;
  countryName:string;
  sourceName:string;
  status:ZoneInfo['status'];
  zoneCount:number;
  zoneTypes:string[];
  sourceUrl:string;
};
export type SavedPlace = Location & {
  id:string;
  savedAt:string;
  score?:number;
  weather?:SavedWeatherSummary;
  airspace?:SavedAirspaceSummary;
  note?:string;
  favorite?:boolean;
};
export type SavedRoute = {
  id:string;
  name:string;
  savedAt:string;
  points:(Location&{id:string})[];
  radiusKm:number;
  distanceKm:number;
};
