import type { Location, ZoneDetail, ZoneInfo } from './types';

const DIPUL_LAYERS=['flugbeschraenkungsgebiete','temporaere_betriebseinschraenkungen','kontrollzonen','flughaefen','flugplaetze','militaerische_anlagen','nationalparks','naturschutzgebiete','vogelschutzgebiete','ffh-gebiete','krankenhaeuser','polizei','justizvollzugsanstalten','industrieanlagen','kraftwerke','windkraftanlagen','modellflugplaetze'];
const language=()=>navigator.language.toLowerCase().split('-')[0];
const countryAt=(p:Location)=>p.lat>=49.35&&p.lat<=50.25&&p.lng>=5.65&&p.lng<=6.65?'LU':p.lat>=47&&p.lat<=55.2&&p.lng>=5.5&&p.lng<=15.5?'DE':p.lat>=27&&p.lat<=44.5&&p.lng>=-18.5&&p.lng<=5?'ES':p.lat>=51.2&&p.lat<=55.6&&p.lng>=-11&&p.lng<=-5?'IE':'XX';
const labels:Record<string,Record<string,string>>={
 en:{FLUGBESCHRAENKUNGSGEBIET:'Flight restriction area',KONTROLLZONE:'Control zone',PROHIBITED:'Prohibited zone',REQ_AUTHORIZATION:'Authorization required',CONDITIONAL:'Conditional zone',COMMON:'Geographical zone'},
 de:{FLUGBESCHRAENKUNGSGEBIET:'Flugbeschränkungsgebiet',KONTROLLZONE:'Kontrollzone',PROHIBITED:'Verbotszone',REQ_AUTHORIZATION:'Genehmigung erforderlich',CONDITIONAL:'Bedingte Zone',COMMON:'Geografisches Gebiet'},
 es:{FLUGBESCHRAENKUNGSGEBIET:'Zona de restricción de vuelo',KONTROLLZONE:'Zona de control',PROHIBITED:'Zona prohibida',REQ_AUTHORIZATION:'Autorización requerida',CONDITIONAL:'Zona condicional',COMMON:'Zona geográfica'},
 fr:{FLUGBESCHRAENKUNGSGEBIET:'Zone de restriction de vol',KONTROLLZONE:'Zone de contrôle',PROHIBITED:'Zone interdite',REQ_AUTHORIZATION:'Autorisation requise',CONDITIONAL:'Zone conditionnelle',COMMON:'Zone géographique'}
};
const translate=(value:string)=>labels[language()]?.[value]??labels.en[value]??value.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
const cleanHtml=(value='')=>{const doc=new DOMParser().parseFromString(value,'text/html');return (doc.body.textContent??'').replace(/\s+/g,' ').trim()};
const base=(code:string,name:string,sourceName:string,sourceUrl:string):ZoneInfo=>({countryCode:code,countryName:name,sourceName,sourceUrl,status:'none',zones:[],checkedAt:new Date().toISOString(),warning:'This is planning information, not legal clearance. Check the official source before takeoff.'});

async function dipul(point:Location):Promise<ZoneInfo>{const result=base('DE',language()==='de'?'Deutschland':'Germany','DIPUL','https://dipul.bund.de/');const d=.035,bbox=`${point.lng-d},${point.lat-d},${point.lng+d},${point.lat+d}`,layers=DIPUL_LAYERS.map(x=>`dipul:${x}`).join(',');const params=new URLSearchParams({SERVICE:'WMS',VERSION:'1.1.1',REQUEST:'GetFeatureInfo',LAYERS:layers,QUERY_LAYERS:layers,STYLES:'',SRS:'EPSG:4326',BBOX:bbox,WIDTH:'256',HEIGHT:'256',X:'128',Y:'128',INFO_FORMAT:'text/plain',FEATURE_COUNT:'50'});const response=await fetch(`https://uas-betrieb.de/geoservices/dipul/wms?${params}`);if(!response.ok)throw new Error('DIPUL query failed');const text=await response.text(),blocks=text.split(/Results for FeatureType/).slice(1);result.zones=blocks.map((block,index)=>{const attrs=Object.fromEntries(block.split('\n').map(line=>line.match(/^([^=]+) = (.*)$/)).filter(Boolean).map(match=>[match![1].trim(),match![2].trim()]));const layer=(block.match(/'[^:]+:([^']+)'/)?.[1]??'zone');return{id:`DE-${index}-${attrs.external_reference??layer}`,name:attrs[`generated_name_${language().toUpperCase()}`]??attrs.generated_name_EN??attrs.name??translate(layer.toUpperCase()),type:translate(attrs.type_code??layer.toUpperCase()),lower:attrs.lower_limit_altitude?`${attrs.lower_limit_altitude} ${attrs.lower_limit_unit??''} ${attrs.lower_limit_alt_ref??''}`:undefined,upper:attrs.upper_limit_altitude?`${attrs.upper_limit_altitude} ${attrs.upper_limit_unit??''} ${attrs.upper_limit_alt_ref??''}`:undefined,legalReference:attrs.legal_ref,source:'DIPUL'} as ZoneDetail});result.status=result.zones.length?'loaded':'none';return result}

async function enaire(point:Location):Promise<ZoneInfo>{const result=base('ES',language()==='es'?'España':'Spain','ENAIRE servAIS','https://aip.enaire.es/AIP/UAS-en.html'),d=.12;const params=new URLSearchParams({geometry:`${point.lng},${point.lat}`,geometryType:'esriGeometryPoint',sr:'4326',tolerance:'3',mapExtent:`${point.lng-d},${point.lat-d},${point.lng+d},${point.lat+d}`,imageDisplay:'800,600,96',layers:'all:0,2,3',returnGeometry:'false',f:'json'});const response=await fetch(`https://servais.enaire.es/insignia/rest/services/NSF_SRV/SRV_UAS_ZG_V0/MapServer/identify?${params}`);if(!response.ok)throw new Error('ENAIRE query failed');const data=await response.json();result.zones=(data.results??[]).map((item:any,index:number)=>{const a=item.attributes??{};return{id:`ES-${item.layerId}-${a.OBJECTID??index}`,name:a.name&&a.name!=='Nulo'?a.name:item.value||item.layerName,type:translate(a.type||a.restriction||'COMMON'),message:cleanHtml(a.message||a.description).slice(0,700),lower:a.lower?`${a.lower} ${a.uom??''} ${a.lowerReference??''}`:undefined,upper:a.upper?`${a.upper} ${a.uom??''} ${a.upperReference??''}`:undefined,contact:[a.email,a.phone].filter((x:string)=>x&&x!=='Nulo').join(' · ')||undefined,source:'ENAIRE',updated:a.updateDateTime||undefined}});result.status=result.zones.length?'loaded':'none';return result}

const insideRing=(point:Location,ring:number[][])=>{let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];if(((yi>point.lat)!==(yj>point.lat))&&(point.lng<(xj-xi)*(point.lat-yi)/(yj-yi)+xi))inside=!inside}return inside};
const contains=(point:Location,geometry:any)=>geometry.type==='Polygon'?insideRing(point,geometry.coordinates[0]):geometry.type==='MultiPolygon'?geometry.coordinates.some((polygon:number[][][])=>insideRing(point,polygon[0])):false;
async function luxembourg(point:Location):Promise<ZoneInfo>{const result=base('LU','Luxembourg','DAC Luxembourg','https://g-o.lu/uas');const response=await fetch(`${import.meta.env.BASE_URL}data/zones/LU.geojson`);if(!response.ok)throw new Error('Offline Luxembourg pack missing');const data=await response.json();result.zones=data.features.filter((feature:any)=>contains(point,feature.geometry)).map((feature:any,index:number)=>{const p=feature.properties;return{id:p.id??`LU-${index}`,name:p.name??'Luxembourg UAS zone',type:translate(p.restriction??p.type??'COMMON'),message:(p.reasons??[]).join(', '),lower:p.lowerLimit!=null?`${p.lowerLimit} ${p.unit??'M'} ${p.lowerReference??''}`:undefined,upper:p.upperLimit!=null?`${p.upperLimit} ${p.unit??'M'} ${p.upperReference??''}`:undefined,contact:p.authority,source:'DAC Luxembourg',updated:p.updated}});result.status=result.zones.length?'loaded':'none';return result}

export async function getOfficialZoneInfo(point:Location):Promise<ZoneInfo>{const code=countryAt(point);try{if(code==='DE')return await dipul(point);if(code==='ES')return await enaire(point);if(code==='LU')return await luxembourg(point);return{...base(code,code==='IE'?'Ireland':'Unknown','Official source directory','#'),status:'unsupported'}}catch{return{...base(code,code,'Official source directory','#'),status:'error'}}}
