import type { ZoneDetail, ZoneInfo } from './types';

export const ZONE_LANGUAGES = ['en','de','fr','es','it','pt','nl','no','sv','da','fi','pl','cs'] as const;
export type ZoneLanguage = typeof ZONE_LANGUAGES[number];
type Severity = NonNullable<ZoneDetail['severity']>;

const languageIndex=(value:string)=>{
  const code=value.toLowerCase().split('-')[0] as ZoneLanguage;
  const index=ZONE_LANGUAGES.indexOf(code);
  return index<0?0:index;
};
export const zoneLanguage=(value:string):ZoneLanguage=>ZONE_LANGUAGES[languageIndex(value)];

const termRows={
 prohibited:['Prohibited zone','Verbotszone','Zone interdite','Zona prohibida','Zona vietata','Zona proibida','Verboden zone','Forbudt sone','Förbjudet område','Forbudt zone','Kielletty alue','Strefa zakazana','Zakázaná zóna'],
 restricted:['Restricted zone','Beschränktes Gebiet','Zone réglementée','Zona restringida','Zona soggetta a restrizioni','Zona restrita','Beperkt gebied','Restriksjonsområde','Restriktionsområde','Restriktionsområde','Rajoitusalue','Strefa ograniczona','Omezená zóna'],
 authorization:['Authorization required','Genehmigung erforderlich','Autorisation requise','Autorización requerida','Autorizzazione richiesta','Autorização necessária','Toestemming vereist','Tillatelse kreves','Tillstånd krävs','Tilladelse kræves','Lupa vaaditaan','Wymagane zezwolenie','Vyžadováno povolení'],
 conditional:['Conditional zone','Bedingtes Gebiet','Zone conditionnelle','Zona condicional','Zona condizionata','Zona condicionada','Voorwaardelijk gebied','Betinget sone','Villkorat område','Betinget område','Ehdollinen alue','Strefa warunkowa','Podmíněná zóna'],
 controlled:['Controlled airspace','Kontrollierter Luftraum','Espace aérien contrôlé','Espacio aéreo controlado','Spazio aereo controllato','Espaço aéreo controlado','Gecontroleerd luchtruim','Kontrollert luftrom','Kontrollerat luftrum','Kontrolleret luftrum','Valvottu ilmatila','Kontrolowana przestrzeń powietrzna','Řízený vzdušný prostor'],
 airport:['Airport','Flughafen','Aéroport','Aeropuerto','Aeroporto','Aeroporto','Luchthaven','Flyplass','Flygplats','Lufthavn','Lentoasema','Lotnisko','Letiště'],
 aerodrome:['Aerodrome','Flugplatz','Aérodrome','Aeródromo','Aviosuperficie','Aeródromo','Luchtvaartterrein','Flyplass','Flygfält','Flyveplads','Lentopaikka','Lądowisko','Letiště'],
 heliport:['Heliport','Hubschrauberlandeplatz','Héliport','Helipuerto','Eliporto','Heliporto','Helikopterhaven','Helikopterplass','Helikopterflygplats','Helikopterlandingsplads','Helikopterikenttä','Lądowisko dla śmigłowców','Heliport'],
 military:['Military area','Militärgebiet','Zone militaire','Zona militar','Zona militare','Zona militar','Militair gebied','Militært område','Militärt område','Militært område','Sotilasalue','Obszar wojskowy','Vojenský prostor'],
 environmental:['Environmental protection area','Umweltschutzgebiet','Zone de protection environnementale','Zona de protección ambiental','Area di protezione ambientale','Área de proteção ambiental','Milieubeschermingsgebied','Miljøvernområde','Miljöskyddsområde','Miljøbeskyttelsesområde','Ympäristönsuojelualue','Obszar ochrony środowiska','Oblast ochrany životního prostředí'],
 temporary:['Temporary restriction','Temporäre Einschränkung','Restriction temporaire','Restricción temporal','Restrizione temporanea','Restrição temporária','Tijdelijke beperking','Midlertidig restriksjon','Tillfällig begränsning','Midlertidig begrænsning','Tilapäinen rajoitus','Ograniczenie tymczasowe','Dočasné omezení'],
 warning:['Warning area','Warngebiet','Zone d’avertissement','Zona de advertencia','Zona di avviso','Zona de aviso','Waarschuwingsgebied','Varslingsområde','Varningsområde','Advarselsområde','Varoitusalue','Strefa ostrzegawcza','Varovná oblast'],
 information:['Information area','Informationsgebiet','Zone d’information','Zona informativa','Zona informativa','Zona informativa','Informatiegebied','Informasjonsområde','Informationsområde','Informationsområde','Tiedotusalue','Strefa informacyjna','Informační oblast'],
 railway:['Railway facility','Bahnanlage','Installation ferroviaire','Infraestructura ferroviaria','Infrastruttura ferroviaria','Infraestrutura ferroviária','Spoorwegvoorziening','Jernbaneanlegg','Järnvägsanläggning','Jernbaneanlæg','Rautatiealue','Obiekt kolejowy','Železniční zařízení'],
 government:['Government facility','Behörde oder Regierungsgebäude','Installation gouvernementale','Instalación gubernamental','Struttura governativa','Instalação governamental','Overheidsgebouw','Offentlig bygning','Myndighetsbyggnad','Myndighedsbygning','Viranomaiskohde','Obiekt rządowy','Vládní objekt'],
 waterway:['Inland waterway','Binnenwasserstraße','Voie navigable intérieure','Vía navegable interior','Via navigabile interna','Via navegável interior','Binnenwaterweg','Innlandsvannvei','Inre vattenväg','Indre vandvej','Sisävesiväylä','Śródlądowa droga wodna','Vnitrozemská vodní cesta'],
 road:['Major road','Hauptverkehrsstraße','Route principale','Carretera principal','Strada principale','Estrada principal','Hoofdweg','Hovedvei','Huvudväg','Hovedvej','Päätie','Droga główna','Hlavní silnice'],
 diplomatic:['Diplomatic mission','Diplomatische Vertretung','Mission diplomatique','Misión diplomática','Missione diplomatica','Missão diplomática','Diplomatieke vertegenwoordiging','Diplomatisk representasjon','Diplomatisk beskickning','Diplomatisk repræsentation','Diplomaattinen edustusto','Placówka dyplomatyczna','Diplomatická mise'],
 recreation:['Bathing or recreation area','Bade- oder Erholungsgebiet','Zone de baignade ou de loisirs','Zona de baño o recreo','Area balneare o ricreativa','Zona balnear ou recreativa','Bad- of recreatiegebied','Bade- eller rekreasjonsområde','Bad- eller rekreationsområde','Bade- eller rekreativt område','Uima- tai virkistysalue','Kąpielisko lub teren rekreacyjny','Oblast koupání nebo rekreace'],
 industrial:['Industrial facility','Industrieanlage','Installation industrielle','Instalación industrial','Impianto industriale','Instalação industrial','Industriële installatie','Industrianlegg','Industrianläggning','Industrianlæg','Teollisuuslaitos','Obiekt przemysłowy','Průmyslový objekt'],
 prison:['Prison or detention facility','Justizvollzugsanstalt','Prison ou centre de détention','Prisión o centro de detención','Carcere o struttura detentiva','Prisão ou centro de detenção','Gevangenis of detentiecentrum','Fengsel eller interneringsanlegg','Fängelse eller häkte','Fængsel eller arrest','Vankila tai säilöönottokeskus','Więzienie lub areszt','Věznice nebo detenční zařízení'],
 powerPlant:['Power plant','Kraftwerk','Centrale électrique','Central eléctrica','Centrale elettrica','Central elétrica','Energiecentrale','Kraftverk','Kraftverk','Kraftværk','Voimalaitos','Elektrownia','Elektrárna'],
 hospital:['Hospital','Krankenhaus','Hôpital','Hospital','Ospedale','Hospital','Ziekenhuis','Sykehus','Sjukhus','Hospital','Sairaala','Szpital','Nemocnice'],
 laboratory:['High-security laboratory','Hochsicherheitslabor','Laboratoire de haute sécurité','Laboratorio de alta seguridad','Laboratorio ad alta sicurezza','Laboratório de alta segurança','Hoogbeveiligd laboratorium','Høysikkerhetslaboratorium','Högsäkerhetslaboratorium','Højsikkerhedslaboratorium','Korkean turvatason laboratorio','Laboratorium wysokiego bezpieczeństwa','Laboratoř s vysokým zabezpečením'],
 nationalPark:['National park','Nationalpark','Parc national','Parque nacional','Parco nazionale','Parque nacional','Nationaal park','Nasjonalpark','Nationalpark','Nationalpark','Kansallispuisto','Park narodowy','Národní park'],
 natureReserve:['Nature reserve','Naturschutzgebiet','Réserve naturelle','Reserva natural','Riserva naturale','Reserva natural','Natuurreservaat','Naturreservat','Naturreservat','Naturreservat','Luonnonsuojelualue','Rezerwat przyrody','Přírodní rezervace'],
 police:['Police facility','Polizeieinrichtung','Installation de police','Instalación policial','Struttura di polizia','Instalação policial','Politiegebouw','Politianlegg','Polisanläggning','Politianlæg','Poliisikohde','Obiekt policji','Policejní objekt'],
 shipping:['Shipping facility','Schifffahrtsanlage','Installation de navigation','Instalación portuaria','Impianto per la navigazione','Instalação de navegação','Scheepvaartvoorziening','Skipsfartsanlegg','Sjöfartsanläggning','Søfartsanlæg','Merenkulun laitos','Obiekt żeglugowy','Plavební zařízení'],
 security:['Security authority facility','Sicherheitsbehörde','Installation d’une autorité de sécurité','Instalación de la autoridad de seguridad','Struttura dell’autorità di sicurezza','Instalação da autoridade de segurança','Beveiligingsdienst','Sikkerhetsmyndighet','Säkerhetsmyndighet','Sikkerhedsmyndighed','Turvallisuusviranomaisen kohde','Obiekt służb bezpieczeństwa','Objekt bezpečnostního úřadu'],
 powerLine:['Power line','Stromleitung','Ligne électrique','Línea eléctrica','Linea elettrica','Linha elétrica','Hoogspanningslijn','Kraftledning','Kraftledning','Elledning','Voimajohto','Linia energetyczna','Elektrické vedení'],
 substation:['Electrical substation','Umspannwerk','Poste électrique','Subestación eléctrica','Sottostazione elettrica','Subestação elétrica','Elektrisch onderstation','Transformatorstasjon','Transformatorstation','Transformerstation','Sähköasema','Stacja elektroenergetyczna','Elektrická rozvodna'],
 birdSanctuary:['Bird protection area','Vogelschutzgebiet','Zone de protection des oiseaux','Zona de protección de aves','Zona di protezione degli uccelli','Zona de proteção de aves','Vogelbeschermingsgebied','Fuglevernområde','Fågelskyddsområde','Fuglebeskyttelsesområde','Lintujensuojelualue','Obszar ochrony ptaków','Ptačí oblast'],
 windTurbine:['Wind turbine','Windkraftanlage','Éolienne','Aerogenerador','Turbina eolica','Turbina eólica','Windturbine','Vindturbin','Vindkraftverk','Vindmølle','Tuulivoimala','Turbina wiatrowa','Větrná elektrárna'],
 residential:['Residential property','Wohngrundstück','Propriété résidentielle','Propiedad residencial','Proprietà residenziale','Propriedade residencial','Woonperceel','Boligeiendom','Bostadsfastighet','Boligejendom','Asuinkiinteistö','Nieruchomość mieszkalna','Rezidenční pozemek'],
 modelAircraft:['Model aircraft site','Modellflugplatz','Terrain d’aéromodélisme','Campo de aeromodelismo','Campo per aeromodelli','Campo de aeromodelismo','Modelvliegterrein','Modellflyplass','Modellflygfält','Modelflyveplads','Lennokkikenttä','Lotnisko modelarskie','Modelářské letiště'],
 hangGlider:['Hang-glider site','Hängegleitergelände','Site de deltaplane','Zona de ala delta','Sito per deltaplano','Local de asa-delta','Deltavliegterrein','Hanggliderområde','Hängflygområde','Drageflyvningsområde','Riippuliitoalue','Teren lotniarski','Plocha pro závěsné létání'],
 uasZone:['UAS geographical zone','Geografisches UAS-Gebiet','Zone géographique UAS','Zona geográfica UAS','Zona geografica UAS','Zona geográfica UAS','Geografische UAS-zone','Geografisk UAS-sone','Geografisk UAS-zon','Geografisk UAS-zone','UAS-ilmatilavyöhyke','Strefa geograficzna UAS','Zeměpisná zóna UAS'],
 facilityGrid:['UAS facility-map grid','UAS-Anlagenkartenraster','Grille de carte des installations UAS','Cuadrícula del mapa de instalaciones UAS','Griglia della mappa delle infrastrutture UAS','Grelha do mapa de instalações UAS','UAS-faciliteitenkaartraster','Rutenett for UAS-anleggskart','Rutnät för UAS-anläggningskarta','Gitter for UAS-anlægskort','UAS-laitoskartan ruudukko','Siatka mapy obiektów UAS','Mřížka mapy zařízení UAS']
} as const;
export type ZoneTerm=keyof typeof termRows;
const term=(key:ZoneTerm,language:string)=>termRows[key][languageIndex(language)];

const ui={
 en:{intersects:'This point intersects {count} official {zones} · {source}',zone:'zone',zones:'zones',none:'No restriction was found in the downloaded or queried official dataset · {source}',handoff:'{country} · official map handoff',unavailable:'{country} · official source unavailable',pilot:'Pilot action',originalName:'Original official name',originalText:'Original official text',layer:'Official layer',lower:'Lower limit',upper:'Upper limit',legal:'Legal reference',authority:'Authority',contact:'Contact',updated:'Source updated',source:'Source',caveat:'Temporary restrictions and current NOTAMs may not be included. Verify current conditions on the official map before flying.',save:'Save location',classification:'Official {source} classification: {type}.',action:'Review the official source, applicable conditions and legal references before flying.',blocked:'The official dataset identifies a prohibition or blocking restriction at this point.',authorization:'Authorization or prior coordination may be required in this zone.',conditional:'Operations in this zone are subject to official conditions.',warning:'This official layer is a warning and may not be a general prohibition.',information:'This official layer provides operational information for this point.',unknown:'The official dataset identifies a zone at this point; verify its exact meaning.'},
 de:{intersects:'Dieser Punkt liegt in {count} offiziellen {zones} · {source}',zone:'Gebiet',zones:'Gebieten',none:'Im heruntergeladenen oder abgefragten offiziellen Datensatz wurde keine Einschränkung gefunden · {source}',handoff:'{country} · Weiterleitung zur offiziellen Karte',unavailable:'{country} · offizielle Quelle nicht verfügbar',pilot:'Pilotenmaßnahme',originalName:'Offizieller Originalname',originalText:'Offizieller Originaltext',layer:'Offizielle Ebene',lower:'Untergrenze',upper:'Obergrenze',legal:'Rechtsgrundlage',authority:'Zuständige Stelle',contact:'Kontakt',updated:'Quelle aktualisiert',source:'Quelle',caveat:'Temporäre Einschränkungen und aktuelle NOTAMs können fehlen. Prüfe vor dem Flug die aktuellen Bedingungen auf der offiziellen Karte.',save:'Ort speichern',classification:'Offizielle {source}-Einstufung: {type}.',action:'Prüfe vor dem Flug die offizielle Quelle, die geltenden Bedingungen und Rechtsgrundlagen.',blocked:'Der offizielle Datensatz weist an diesem Punkt ein Verbot oder eine sperrende Einschränkung aus.',authorization:'In diesem Gebiet kann eine Genehmigung oder vorherige Koordination erforderlich sein.',conditional:'Flüge in diesem Gebiet unterliegen offiziellen Bedingungen.',warning:'Diese offizielle Ebene ist eine Warnung und nicht zwingend ein allgemeines Verbot.',information:'Diese offizielle Ebene enthält betriebliche Informationen für diesen Punkt.',unknown:'Der offizielle Datensatz weist hier ein Gebiet aus; prüfe dessen genaue Bedeutung.'},
 fr:{intersects:'Ce point se trouve dans {count} {zones} officielles · {source}',zone:'zone',zones:'zones',none:'Aucune restriction n’a été trouvée dans le jeu de données officiel téléchargé ou interrogé · {source}',handoff:'{country} · redirection vers la carte officielle',unavailable:'{country} · source officielle indisponible',pilot:'Action du pilote',originalName:'Nom officiel original',originalText:'Texte officiel original',layer:'Couche officielle',lower:'Limite inférieure',upper:'Limite supérieure',legal:'Référence juridique',authority:'Autorité',contact:'Contact',updated:'Source mise à jour',source:'Source',caveat:'Les restrictions temporaires et les NOTAM en vigueur peuvent être absents. Vérifiez les conditions actuelles sur la carte officielle avant le vol.',save:'Enregistrer le lieu',classification:'Classification officielle {source} : {type}.',action:'Consultez la source officielle, les conditions applicables et les références juridiques avant le vol.',blocked:'Le jeu de données officiel indique une interdiction ou une restriction bloquante à ce point.',authorization:'Une autorisation ou une coordination préalable peut être requise dans cette zone.',conditional:'Les opérations dans cette zone sont soumises à des conditions officielles.',warning:'Cette couche officielle constitue un avertissement et pas nécessairement une interdiction générale.',information:'Cette couche officielle fournit des informations opérationnelles pour ce point.',unknown:'Le jeu de données officiel indique une zone à ce point ; vérifiez sa signification exacte.'},
 es:{intersects:'Este punto se encuentra en {count} {zones} oficiales · {source}',zone:'zona',zones:'zonas',none:'No se encontró ninguna restricción en el conjunto de datos oficial descargado o consultado · {source}',handoff:'{country} · acceso al mapa oficial',unavailable:'{country} · fuente oficial no disponible',pilot:'Acción del piloto',originalName:'Nombre oficial original',originalText:'Texto oficial original',layer:'Capa oficial',lower:'Límite inferior',upper:'Límite superior',legal:'Referencia legal',authority:'Autoridad',contact:'Contacto',updated:'Fuente actualizada',source:'Fuente',caveat:'Es posible que no se incluyan restricciones temporales ni NOTAM vigentes. Verifica las condiciones actuales en el mapa oficial antes de volar.',save:'Guardar ubicación',classification:'Clasificación oficial de {source}: {type}.',action:'Consulta la fuente oficial, las condiciones aplicables y las referencias legales antes de volar.',blocked:'El conjunto de datos oficial indica una prohibición o restricción que impide el vuelo en este punto.',authorization:'En esta zona puede ser necesaria una autorización o coordinación previa.',conditional:'Las operaciones en esta zona están sujetas a condiciones oficiales.',warning:'Esta capa oficial es una advertencia y no necesariamente una prohibición general.',information:'Esta capa oficial proporciona información operativa para este punto.',unknown:'El conjunto de datos oficial identifica una zona en este punto; verifica su significado exacto.'},
 it:{intersects:'Questo punto si trova in {count} {zones} ufficiali · {source}',zone:'zona',zones:'zone',none:'Nessuna restrizione trovata nel set di dati ufficiale scaricato o interrogato · {source}',handoff:'{country} · collegamento alla mappa ufficiale',unavailable:'{country} · fonte ufficiale non disponibile',pilot:'Azione del pilota',originalName:'Nome ufficiale originale',originalText:'Testo ufficiale originale',layer:'Livello ufficiale',lower:'Limite inferiore',upper:'Limite superiore',legal:'Riferimento normativo',authority:'Autorità',contact:'Contatto',updated:'Fonte aggiornata',source:'Fonte',caveat:'Le restrizioni temporanee e i NOTAM in vigore potrebbero non essere inclusi. Verifica le condizioni attuali sulla mappa ufficiale prima del volo.',save:'Salva posizione',classification:'Classificazione ufficiale {source}: {type}.',action:'Consulta la fonte ufficiale, le condizioni applicabili e i riferimenti normativi prima del volo.',blocked:'Il set di dati ufficiale indica un divieto o una restrizione bloccante in questo punto.',authorization:'In questa zona può essere necessaria un’autorizzazione o un coordinamento preventivo.',conditional:'Le operazioni in questa zona sono soggette a condizioni ufficiali.',warning:'Questo livello ufficiale è un avviso e non necessariamente un divieto generale.',information:'Questo livello ufficiale fornisce informazioni operative per questo punto.',unknown:'Il set di dati ufficiale identifica una zona in questo punto; verificane il significato esatto.'},
 pt:{intersects:'Este ponto intersecta {count} {zones} oficiais · {source}',zone:'zona',zones:'zonas',none:'Não foi encontrada nenhuma restrição no conjunto de dados oficial descarregado ou consultado · {source}',handoff:'{country} · ligação ao mapa oficial',unavailable:'{country} · fonte oficial indisponível',pilot:'Ação do piloto',originalName:'Nome oficial original',originalText:'Texto oficial original',layer:'Camada oficial',lower:'Limite inferior',upper:'Limite superior',legal:'Referência legal',authority:'Autoridade',contact:'Contacto',updated:'Fonte atualizada',source:'Fonte',caveat:'As restrições temporárias e os NOTAM em vigor podem não estar incluídos. Verifique as condições atuais no mapa oficial antes do voo.',save:'Guardar local',classification:'Classificação oficial de {source}: {type}.',action:'Consulte a fonte oficial, as condições aplicáveis e as referências legais antes do voo.',blocked:'O conjunto de dados oficial indica uma proibição ou restrição impeditiva neste ponto.',authorization:'Nesta zona pode ser necessária autorização ou coordenação prévia.',conditional:'As operações nesta zona estão sujeitas a condições oficiais.',warning:'Esta camada oficial é um aviso e não necessariamente uma proibição geral.',information:'Esta camada oficial fornece informações operacionais para este ponto.',unknown:'O conjunto de dados oficial identifica uma zona neste ponto; verifique o significado exato.'},
 nl:{intersects:'Dit punt ligt in {count} officiële {zones} · {source}',zone:'zone',zones:'zones',none:'In de gedownloade of bevraagde officiële gegevens is geen beperking gevonden · {source}',handoff:'{country} · doorverwijzing naar officiële kaart',unavailable:'{country} · officiële bron niet beschikbaar',pilot:'Actie voor de piloot',originalName:'Oorspronkelijke officiële naam',originalText:'Oorspronkelijke officiële tekst',layer:'Officiële laag',lower:'Ondergrens',upper:'Bovengrens',legal:'Juridische verwijzing',authority:'Autoriteit',contact:'Contact',updated:'Bron bijgewerkt',source:'Bron',caveat:'Tijdelijke beperkingen en actuele NOTAMs kunnen ontbreken. Controleer vóór de vlucht de actuele omstandigheden op de officiële kaart.',save:'Locatie opslaan',classification:'Officiële classificatie van {source}: {type}.',action:'Controleer vóór de vlucht de officiële bron, toepasselijke voorwaarden en juridische verwijzingen.',blocked:'De officiële gegevens wijzen op dit punt een verbod of blokkerende beperking aan.',authorization:'In deze zone kan toestemming of voorafgaande coördinatie nodig zijn.',conditional:'Vluchten in deze zone zijn onderworpen aan officiële voorwaarden.',warning:'Deze officiële laag is een waarschuwing en niet noodzakelijk een algemeen verbod.',information:'Deze officiële laag geeft operationele informatie voor dit punt.',unknown:'De officiële gegevens tonen hier een zone; controleer de precieze betekenis.'},
 no:{intersects:'Dette punktet ligger i {count} offisielle {zones} · {source}',zone:'sone',zones:'soner',none:'Ingen restriksjon ble funnet i det nedlastede eller forespurte offisielle datasettet · {source}',handoff:'{country} · videre til offisielt kart',unavailable:'{country} · offisiell kilde utilgjengelig',pilot:'Tiltak for pilot',originalName:'Opprinnelig offisielt navn',originalText:'Opprinnelig offisiell tekst',layer:'Offisielt lag',lower:'Nedre grense',upper:'Øvre grense',legal:'Juridisk referanse',authority:'Myndighet',contact:'Kontakt',updated:'Kilde oppdatert',source:'Kilde',caveat:'Midlertidige restriksjoner og gjeldende NOTAM kan mangle. Kontroller gjeldende forhold på det offisielle kartet før flyging.',save:'Lagre sted',classification:'Offisiell klassifisering fra {source}: {type}.',action:'Kontroller offisiell kilde, gjeldende vilkår og juridiske referanser før flyging.',blocked:'Det offisielle datasettet angir et forbud eller en blokkerende restriksjon på dette punktet.',authorization:'Tillatelse eller forhåndskoordinering kan være nødvendig i denne sonen.',conditional:'Operasjoner i denne sonen er underlagt offisielle vilkår.',warning:'Dette offisielle laget er en advarsel og ikke nødvendigvis et generelt forbud.',information:'Dette offisielle laget gir operativ informasjon for dette punktet.',unknown:'Det offisielle datasettet viser en sone her; kontroller den nøyaktige betydningen.'},
 sv:{intersects:'Den här punkten ligger i {count} officiella {zones} · {source}',zone:'zon',zones:'zoner',none:'Ingen begränsning hittades i den hämtade eller efterfrågade officiella datamängden · {source}',handoff:'{country} · vidare till officiell karta',unavailable:'{country} · officiell källa ej tillgänglig',pilot:'Åtgärd för pilot',originalName:'Ursprungligt officiellt namn',originalText:'Ursprunglig officiell text',layer:'Officiellt lager',lower:'Undre gräns',upper:'Övre gräns',legal:'Rättslig hänvisning',authority:'Myndighet',contact:'Kontakt',updated:'Källa uppdaterad',source:'Källa',caveat:'Tillfälliga begränsningar och aktuella NOTAM kan saknas. Kontrollera aktuella villkor på den officiella kartan före flygning.',save:'Spara plats',classification:'Officiell klassificering från {source}: {type}.',action:'Kontrollera den officiella källan, tillämpliga villkor och rättsliga hänvisningar före flygning.',blocked:'Den officiella datamängden anger ett förbud eller en blockerande begränsning vid den här punkten.',authorization:'Tillstånd eller förhandskoordinering kan krävas i den här zonen.',conditional:'Flygning i den här zonen omfattas av officiella villkor.',warning:'Det här officiella lagret är en varning och inte nödvändigtvis ett allmänt förbud.',information:'Det här officiella lagret ger operativ information för den här punkten.',unknown:'Den officiella datamängden visar en zon här; kontrollera dess exakta innebörd.'},
 da:{intersects:'Dette punkt ligger i {count} officielle {zones} · {source}',zone:'zone',zones:'zoner',none:'Der blev ikke fundet nogen begrænsning i det downloadede eller forespurgte officielle datasæt · {source}',handoff:'{country} · videre til officielt kort',unavailable:'{country} · officiel kilde utilgængelig',pilot:'Handling for pilot',originalName:'Oprindeligt officielt navn',originalText:'Oprindelig officiel tekst',layer:'Officielt lag',lower:'Nedre grænse',upper:'Øvre grænse',legal:'Juridisk reference',authority:'Myndighed',contact:'Kontakt',updated:'Kilde opdateret',source:'Kilde',caveat:'Midlertidige begrænsninger og aktuelle NOTAM kan mangle. Kontrollér de aktuelle forhold på det officielle kort før flyvning.',save:'Gem placering',classification:'Officiel klassifikation fra {source}: {type}.',action:'Kontrollér den officielle kilde, gældende vilkår og juridiske referencer før flyvning.',blocked:'Det officielle datasæt angiver et forbud eller en blokerende begrænsning på dette punkt.',authorization:'Tilladelse eller forudgående koordinering kan være nødvendig i denne zone.',conditional:'Flyvning i denne zone er underlagt officielle vilkår.',warning:'Dette officielle lag er en advarsel og ikke nødvendigvis et generelt forbud.',information:'Dette officielle lag giver operationelle oplysninger for dette punkt.',unknown:'Det officielle datasæt viser en zone her; kontrollér dens præcise betydning.'},
 fi:{intersects:'Tämä piste sijaitsee {count} virallisella {zones} · {source}',zone:'vyöhykkeellä',zones:'vyöhykkeellä',none:'Ladatusta tai kysellystä virallisesta aineistosta ei löytynyt rajoitusta · {source}',handoff:'{country} · siirtyminen viralliselle kartalle',unavailable:'{country} · virallinen lähde ei ole käytettävissä',pilot:'Kauko-ohjaajan toimenpide',originalName:'Alkuperäinen virallinen nimi',originalText:'Alkuperäinen virallinen teksti',layer:'Virallinen taso',lower:'Alaraja',upper:'Yläraja',legal:'Oikeudellinen viite',authority:'Viranomainen',contact:'Yhteystiedot',updated:'Lähde päivitetty',source:'Lähde',caveat:'Tilapäiset rajoitukset ja voimassa olevat NOTAMit voivat puuttua. Tarkista ajantasaiset ehdot viralliselta kartalta ennen lentoa.',save:'Tallenna sijainti',classification:'Lähteen {source} virallinen luokitus: {type}.',action:'Tarkista virallinen lähde, sovellettavat ehdot ja oikeudelliset viitteet ennen lentoa.',blocked:'Virallinen aineisto osoittaa tässä pisteessä kiellon tai lennon estävän rajoituksen.',authorization:'Tällä vyöhykkeellä voidaan vaatia lupa tai ennakkokoordinointi.',conditional:'Toimintaan tällä vyöhykkeellä sovelletaan virallisia ehtoja.',warning:'Tämä virallinen taso on varoitus eikä välttämättä yleinen kielto.',information:'Tämä virallinen taso antaa toiminnallisia tietoja tästä pisteestä.',unknown:'Virallinen aineisto osoittaa tässä vyöhykkeen; tarkista sen täsmällinen merkitys.'},
 pl:{intersects:'Ten punkt znajduje się w {count} oficjalnych {zones} · {source}',zone:'strefie',zones:'strefach',none:'W pobranym lub odpytanym oficjalnym zbiorze danych nie znaleziono ograniczenia · {source}',handoff:'{country} · przejście do oficjalnej mapy',unavailable:'{country} · oficjalne źródło niedostępne',pilot:'Działanie pilota',originalName:'Oryginalna nazwa urzędowa',originalText:'Oryginalny tekst urzędowy',layer:'Oficjalna warstwa',lower:'Dolna granica',upper:'Górna granica',legal:'Podstawa prawna',authority:'Organ właściwy',contact:'Kontakt',updated:'Aktualizacja źródła',source:'Źródło',caveat:'Tymczasowe ograniczenia i aktualne NOTAM-y mogą nie być uwzględnione. Przed lotem sprawdź aktualne warunki na oficjalnej mapie.',save:'Zapisz lokalizację',classification:'Oficjalna klasyfikacja {source}: {type}.',action:'Przed lotem sprawdź oficjalne źródło, obowiązujące warunki i podstawy prawne.',blocked:'Oficjalny zbiór danych wskazuje w tym punkcie zakaz lub ograniczenie uniemożliwiające lot.',authorization:'W tej strefie może być wymagane zezwolenie lub wcześniejsza koordynacja.',conditional:'Operacje w tej strefie podlegają oficjalnym warunkom.',warning:'Ta oficjalna warstwa jest ostrzeżeniem i nie musi oznaczać ogólnego zakazu.',information:'Ta oficjalna warstwa zawiera informacje operacyjne dla tego punktu.',unknown:'Oficjalny zbiór danych wskazuje tu strefę; sprawdź jej dokładne znaczenie.'},
 cs:{intersects:'Tento bod leží v {count} oficiálních {zones} · {source}',zone:'zóně',zones:'zónách',none:'Ve staženém nebo dotázaném oficiálním datovém souboru nebylo nalezeno žádné omezení · {source}',handoff:'{country} · přechod na oficiální mapu',unavailable:'{country} · oficiální zdroj není dostupný',pilot:'Úkon pilota',originalName:'Původní oficiální název',originalText:'Původní oficiální text',layer:'Oficiální vrstva',lower:'Dolní mez',upper:'Horní mez',legal:'Právní odkaz',authority:'Příslušný orgán',contact:'Kontakt',updated:'Aktualizace zdroje',source:'Zdroj',caveat:'Dočasná omezení a aktuální NOTAMy nemusí být zahrnuty. Před letem ověřte aktuální podmínky na oficiální mapě.',save:'Uložit polohu',classification:'Oficiální klasifikace {source}: {type}.',action:'Před letem ověřte oficiální zdroj, platné podmínky a právní odkazy.',blocked:'Oficiální datový soubor v tomto bodě uvádí zákaz nebo omezení znemožňující let.',authorization:'V této zóně může být vyžadováno povolení nebo předchozí koordinace.',conditional:'Provoz v této zóně podléhá oficiálním podmínkám.',warning:'Tato oficiální vrstva je varováním a nemusí představovat obecný zákaz.',information:'Tato oficiální vrstva poskytuje provozní informace pro tento bod.',unknown:'Oficiální datový soubor zde uvádí zónu; ověřte její přesný význam.'}
} as const;

export type ZoneUiKey=keyof typeof ui.en;
export const zoneText=(language:string,key:ZoneUiKey,values:Record<string,string|number>={})=>{
  let value:string=ui[zoneLanguage(language)][key];
  for(const [name,replacement] of Object.entries(values))value=value.replaceAll(`{${name}}`,String(replacement));
  return value;
};

const normalized=(value='')=>value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_');
const termPatterns:[RegExp,ZoneTerm][]=[
 [/BAHN|RAILWAY/,'railway'],[/SICHERHEIT|SECURITY/,'security'],[/INTERNATIONALE?_ORGANISATION|INTERNATIONAL_ORGANI[ZS]ATION/,'government'],[/BEHOERD|GOVERNMENT|AUTHORITY/,'government'],[/BINNENWASSER|INLAND_WATER/,'waterway'],
 [/BUNDESAUTOBAHN|BUNDESSTRASSE|MOTORWAY|ROAD/,'road'],[/DIPLOMAT|EMBASS|CONSUL/,'diplomatic'],[/FFH|HABITAT|ENVIRON|ECOLOG/,'environmental'],
 [/FLUGBESCHRAENK|PROHIB|INTERDIT|VIETAT|VERBOT/,'prohibited'],[/FLUGHAFEN|AIRPORT/,'airport'],[/FLUGPLATZ|AERODROME|AERODROM/,'aerodrome'],
 [/HELIPORT|HELIPAD/,'heliport'],[/FREIBAD|BATHING|RECREATION/,'recreation'],[/HAENGEGL|HANG_GLID/,'hangGlider'],[/INDUSTR/,'industrial'],
 [/JUSTIZ|PRISON|DETENTION/,'prison'],[/KONTROLLZONE|CONTROL_ZONE|CONTROLLED_AIRSPACE/,'controlled'],[/KRAFTWERK|POWER_PLANT/,'powerPlant'],
 [/KRANKENHAUS|HOSPITAL/,'hospital'],[/LABOR/,'laboratory'],[/MILITA|MILITAR/,'military'],[/MODELLFLUG|MODEL_AIRCRAFT/,'modelAircraft'],
 [/NATIONALPARK|NATIONAL_PARK/,'nationalPark'],[/NATURSCHUTZ|NATURE_RESERVE/,'natureReserve'],[/POLIZEI|POLICE/,'police'],
 [/SCHIFFFAHRT|SHIPPING/,'shipping'],[/SEEWASSER|SEA_WATERWAY/,'waterway'],[/STROMLEIT|POWER_LINE/,'powerLine'],
 [/TEMPORA|TEMPORARY/,'temporary'],[/UMSPANN|SUBSTATION/,'substation'],[/VOGELSCHUTZ|BIRD/,'birdSanctuary'],[/WINDKRAFT|WIND_TURBINE/,'windTurbine'],
 [/WOHNGRUND|RESIDENTIAL/,'residential'],[/REQ_AUTH|AUTHORISATION|AUTHORIZATION_REQUIRED|PERMISSION_REQUIRED/,'authorization'],
 [/CONDITIONAL|CONDITION/,'conditional'],[/RESTRICT/,'restricted'],[/WARNING|ADVISORY|ATTENTION/,'warning'],[/INFORMATION|NOTICE/,'information'],
 [/FACILITY_MAP|AUTHORIZATION_CEILING/,'facilityGrid'],[/UAS|DRONE_ZONE|COMMON|GEOGRAPHICAL_ZONE/,'uasZone']
];

export const zoneTermKey=(value?:string):ZoneTerm=>{
  const token=normalized(value);
  return termPatterns.find(([pattern])=>pattern.test(token))?.[1]??'uasZone';
};
export const translateZoneTerm=(value:string|undefined,language:string)=>term(zoneTermKey(value),language);

const genericNames=/^(UNKNOWN|UAS|DRONE|ZONE|FEATURE|RESTRICTION|RESTRICTION UAS|FRENCH UAS RESTRICTION|PORTUGAL UAS|SWISS UAS|IRELAND UAS|LUXEMBOURG UAS|DANISH DRONE ZONE|BAHNANLAGE)$/i;
const looksGeneric=(value:string|undefined,typeValue:string|undefined)=>{
  if(!value)return true;
  const name=normalized(value),type=normalized(typeValue);
  return genericNames.test(value.trim())||name===type||zoneTermKey(name)!=='uasZone'&&name.length<45;
};

const operationalMessage=(severity:Severity|undefined,language:string)=>zoneText(language,severity??'unknown');

export function localizeZoneDetail(zone:ZoneDetail,language:string):ZoneDetail{
  const code=zone.categoryCode??zone.type??zone.officialLayerName;
  const type=translateZoneTerm(code,language);
  const originalName=zone.originalName??zone.name;
  const name=zone.nameLocalizedLanguage===zoneLanguage(language)
    ? zone.name
    : looksGeneric(originalName,code)
      ? type
      : originalName.includes(type)?originalName:`${originalName} · ${type}`;
  const localizedMessage=zone.messageLocalizedLanguage===zoneLanguage(language)?zone.message:operationalMessage(zone.severity,language);
  return{
    ...zone,
    name,
    originalName,
    type,
    message:localizedMessage,
    originalMessage:zone.originalMessage??(zone.messageLocalizedLanguage?undefined:zone.message),
    pilotAction:zoneText(language,'action'),
    officialLayerName:zone.officialLayerName?translateZoneTerm(zone.layerCode??zone.officialLayerName,language):undefined
  };
}

export function localizeZoneInfo(info:ZoneInfo,language:string):ZoneInfo{
  let countryName=info.countryName;
  try{countryName=new Intl.DisplayNames([zoneLanguage(language)],{type:'region'}).of(info.countryCode)??countryName}catch{}
  return{...info,countryName,zones:info.zones.map(zone=>localizeZoneDetail(zone,language))};
}
